/*
 * This file is generated by jOOQ.
*/
package com.rbkmoney.newway.domain.enums;


import com.rbkmoney.newway.domain.Nw;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum BankCardPaymentSystem implements EnumType {

    visa("visa"),

    mastercard("mastercard"),

    visaelectron("visaelectron"),

    maestro("maestro"),

    forbrugsforeningen("forbrugsforeningen"),

    dankort("dankort"),

    amex("amex"),

    dinersclub("dinersclub"),

    discover("discover"),

    unionpay("unionpay"),

    jcb("jcb"),

    nspkmir("nspkmir");

    private final String literal;

    private BankCardPaymentSystem(String literal) {
        this.literal = literal;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return getSchema() == null ? null : getSchema().getCatalog();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Nw.NW;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String getName() {
        return "bank_card_payment_system";
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String getLiteral() {
        return literal;
    }
}
