/*
 * This file is generated by jOOQ.
*/
package com.rbkmoney.newway.domain.routines;


import com.rbkmoney.newway.domain.Nw;
import com.rbkmoney.newway.domain.enums.CashFlowAccount;
import com.rbkmoney.newway.domain.enums.PaymentChangeType;
import com.rbkmoney.newway.domain.tables.records.CashFlowRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GetCashflowSum extends AbstractRoutine<Long> {

    private static final long serialVersionUID = -1748964883;

    /**
     * The parameter <code>nw.get_cashflow_sum.RETURN_VALUE</code>.
     */
    public static final Parameter<Long> RETURN_VALUE = createParameter("RETURN_VALUE", org.jooq.impl.SQLDataType.BIGINT, false, false);

    /**
     * The parameter <code>nw.get_cashflow_sum._cash_flow</code>.
     */
    public static final Parameter<CashFlowRecord> _CASH_FLOW = createParameter("_cash_flow", com.rbkmoney.newway.domain.tables.CashFlow.CASH_FLOW.getDataType(), false, false);

    /**
     * The parameter <code>nw.get_cashflow_sum.obj_type</code>.
     */
    public static final Parameter<PaymentChangeType> OBJ_TYPE = createParameter("obj_type", org.jooq.util.postgres.PostgresDataType.VARCHAR.asEnumDataType(com.rbkmoney.newway.domain.enums.PaymentChangeType.class), false, false);

    /**
     * The parameter <code>nw.get_cashflow_sum.source_account_type</code>.
     */
    public static final Parameter<CashFlowAccount> SOURCE_ACCOUNT_TYPE = createParameter("source_account_type", org.jooq.util.postgres.PostgresDataType.VARCHAR.asEnumDataType(com.rbkmoney.newway.domain.enums.CashFlowAccount.class), false, false);

    /**
     * The parameter <code>nw.get_cashflow_sum.source_account_type_values</code>.
     */
    public static final Parameter<String[]> SOURCE_ACCOUNT_TYPE_VALUES = createParameter("source_account_type_values", org.jooq.impl.SQLDataType.VARCHAR.getArrayDataType(), false, false);

    /**
     * The parameter <code>nw.get_cashflow_sum.destination_account_type</code>.
     */
    public static final Parameter<CashFlowAccount> DESTINATION_ACCOUNT_TYPE = createParameter("destination_account_type", org.jooq.util.postgres.PostgresDataType.VARCHAR.asEnumDataType(com.rbkmoney.newway.domain.enums.CashFlowAccount.class), false, false);

    /**
     * The parameter <code>nw.get_cashflow_sum.destination_account_type_values</code>.
     */
    public static final Parameter<String[]> DESTINATION_ACCOUNT_TYPE_VALUES = createParameter("destination_account_type_values", org.jooq.impl.SQLDataType.VARCHAR.getArrayDataType(), false, false);

    /**
     * Create a new routine call instance
     */
    public GetCashflowSum() {
        super("get_cashflow_sum", Nw.NW, org.jooq.impl.SQLDataType.BIGINT);

        setReturnParameter(RETURN_VALUE);
        addInParameter(_CASH_FLOW);
        addInParameter(OBJ_TYPE);
        addInParameter(SOURCE_ACCOUNT_TYPE);
        addInParameter(SOURCE_ACCOUNT_TYPE_VALUES);
        addInParameter(DESTINATION_ACCOUNT_TYPE);
        addInParameter(DESTINATION_ACCOUNT_TYPE_VALUES);
    }

    /**
     * Set the <code>_cash_flow</code> parameter IN value to the routine
     */
    public void set_CashFlow(CashFlowRecord value) {
        setValue(_CASH_FLOW, value);
    }

    /**
     * Set the <code>_cash_flow</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public void set_CashFlow(Field<CashFlowRecord> field) {
        setField(_CASH_FLOW, field);
    }

    /**
     * Set the <code>obj_type</code> parameter IN value to the routine
     */
    public void setObjType(PaymentChangeType value) {
        setValue(OBJ_TYPE, value);
    }

    /**
     * Set the <code>obj_type</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public void setObjType(Field<PaymentChangeType> field) {
        setField(OBJ_TYPE, field);
    }

    /**
     * Set the <code>source_account_type</code> parameter IN value to the routine
     */
    public void setSourceAccountType(CashFlowAccount value) {
        setValue(SOURCE_ACCOUNT_TYPE, value);
    }

    /**
     * Set the <code>source_account_type</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public void setSourceAccountType(Field<CashFlowAccount> field) {
        setField(SOURCE_ACCOUNT_TYPE, field);
    }

    /**
     * Set the <code>source_account_type_values</code> parameter IN value to the routine
     */
    public void setSourceAccountTypeValues(String... value) {
        setValue(SOURCE_ACCOUNT_TYPE_VALUES, value);
    }

    /**
     * Set the <code>source_account_type_values</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public void setSourceAccountTypeValues(Field<String[]> field) {
        setField(SOURCE_ACCOUNT_TYPE_VALUES, field);
    }

    /**
     * Set the <code>destination_account_type</code> parameter IN value to the routine
     */
    public void setDestinationAccountType(CashFlowAccount value) {
        setValue(DESTINATION_ACCOUNT_TYPE, value);
    }

    /**
     * Set the <code>destination_account_type</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public void setDestinationAccountType(Field<CashFlowAccount> field) {
        setField(DESTINATION_ACCOUNT_TYPE, field);
    }

    /**
     * Set the <code>destination_account_type_values</code> parameter IN value to the routine
     */
    public void setDestinationAccountTypeValues(String... value) {
        setValue(DESTINATION_ACCOUNT_TYPE_VALUES, value);
    }

    /**
     * Set the <code>destination_account_type_values</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public void setDestinationAccountTypeValues(Field<String[]> field) {
        setField(DESTINATION_ACCOUNT_TYPE_VALUES, field);
    }
}
