/*
 * This file is generated by jOOQ.
*/
package com.rbkmoney.newway.domain.tables.records;


import com.rbkmoney.newway.domain.enums.ContractStatus;
import com.rbkmoney.newway.domain.enums.RepresentativeDocument;
import com.rbkmoney.newway.domain.tables.Contract;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContractRecord extends UpdatableRecordImpl<ContractRecord> {

    private static final long serialVersionUID = -1754258086;

    /**
     * Setter for <code>nw.contract.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>nw.contract.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>nw.contract.event_id</code>.
     */
    public void setEventId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>nw.contract.event_id</code>.
     */
    public Long getEventId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>nw.contract.event_created_at</code>.
     */
    public void setEventCreatedAt(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>nw.contract.event_created_at</code>.
     */
    public LocalDateTime getEventCreatedAt() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>nw.contract.contract_id</code>.
     */
    public void setContractId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>nw.contract.contract_id</code>.
     */
    public String getContractId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>nw.contract.party_id</code>.
     */
    public void setPartyId(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>nw.contract.party_id</code>.
     */
    public String getPartyId() {
        return (String) get(4);
    }

    /**
     * Setter for <code>nw.contract.payment_institution_id</code>.
     */
    public void setPaymentInstitutionId(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>nw.contract.payment_institution_id</code>.
     */
    public Integer getPaymentInstitutionId() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>nw.contract.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>nw.contract.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>nw.contract.valid_since</code>.
     */
    public void setValidSince(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>nw.contract.valid_since</code>.
     */
    public LocalDateTime getValidSince() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>nw.contract.valid_until</code>.
     */
    public void setValidUntil(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>nw.contract.valid_until</code>.
     */
    public LocalDateTime getValidUntil() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>nw.contract.status</code>.
     */
    public void setStatus(ContractStatus value) {
        set(9, value);
    }

    /**
     * Getter for <code>nw.contract.status</code>.
     */
    public ContractStatus getStatus() {
        return (ContractStatus) get(9);
    }

    /**
     * Setter for <code>nw.contract.status_terminated_at</code>.
     */
    public void setStatusTerminatedAt(LocalDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>nw.contract.status_terminated_at</code>.
     */
    public LocalDateTime getStatusTerminatedAt() {
        return (LocalDateTime) get(10);
    }

    /**
     * Setter for <code>nw.contract.terms_id</code>.
     */
    public void setTermsId(Integer value) {
        set(11, value);
    }

    /**
     * Getter for <code>nw.contract.terms_id</code>.
     */
    public Integer getTermsId() {
        return (Integer) get(11);
    }

    /**
     * Setter for <code>nw.contract.legal_agreement_signed_at</code>.
     */
    public void setLegalAgreementSignedAt(LocalDateTime value) {
        set(12, value);
    }

    /**
     * Getter for <code>nw.contract.legal_agreement_signed_at</code>.
     */
    public LocalDateTime getLegalAgreementSignedAt() {
        return (LocalDateTime) get(12);
    }

    /**
     * Setter for <code>nw.contract.legal_agreement_id</code>.
     */
    public void setLegalAgreementId(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>nw.contract.legal_agreement_id</code>.
     */
    public String getLegalAgreementId() {
        return (String) get(13);
    }

    /**
     * Setter for <code>nw.contract.legal_agreement_valid_until</code>.
     */
    public void setLegalAgreementValidUntil(LocalDateTime value) {
        set(14, value);
    }

    /**
     * Getter for <code>nw.contract.legal_agreement_valid_until</code>.
     */
    public LocalDateTime getLegalAgreementValidUntil() {
        return (LocalDateTime) get(14);
    }

    /**
     * Setter for <code>nw.contract.report_act_schedule_id</code>.
     */
    public void setReportActScheduleId(Integer value) {
        set(15, value);
    }

    /**
     * Getter for <code>nw.contract.report_act_schedule_id</code>.
     */
    public Integer getReportActScheduleId() {
        return (Integer) get(15);
    }

    /**
     * Setter for <code>nw.contract.report_act_signer_position</code>.
     */
    public void setReportActSignerPosition(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>nw.contract.report_act_signer_position</code>.
     */
    public String getReportActSignerPosition() {
        return (String) get(16);
    }

    /**
     * Setter for <code>nw.contract.report_act_signer_full_name</code>.
     */
    public void setReportActSignerFullName(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>nw.contract.report_act_signer_full_name</code>.
     */
    public String getReportActSignerFullName() {
        return (String) get(17);
    }

    /**
     * Setter for <code>nw.contract.report_act_signer_document</code>.
     */
    public void setReportActSignerDocument(RepresentativeDocument value) {
        set(18, value);
    }

    /**
     * Getter for <code>nw.contract.report_act_signer_document</code>.
     */
    public RepresentativeDocument getReportActSignerDocument() {
        return (RepresentativeDocument) get(18);
    }

    /**
     * Setter for <code>nw.contract.report_act_signer_doc_power_of_attorney_signed_at</code>.
     */
    public void setReportActSignerDocPowerOfAttorneySignedAt(LocalDateTime value) {
        set(19, value);
    }

    /**
     * Getter for <code>nw.contract.report_act_signer_doc_power_of_attorney_signed_at</code>.
     */
    public LocalDateTime getReportActSignerDocPowerOfAttorneySignedAt() {
        return (LocalDateTime) get(19);
    }

    /**
     * Setter for <code>nw.contract.report_act_signer_doc_power_of_attorney_legal_agreement_id</code>.
     */
    public void setReportActSignerDocPowerOfAttorneyLegalAgreementId(String value) {
        set(20, value);
    }

    /**
     * Getter for <code>nw.contract.report_act_signer_doc_power_of_attorney_legal_agreement_id</code>.
     */
    public String getReportActSignerDocPowerOfAttorneyLegalAgreementId() {
        return (String) get(20);
    }

    /**
     * Setter for <code>nw.contract.report_act_signer_doc_power_of_attorney_valid_until</code>.
     */
    public void setReportActSignerDocPowerOfAttorneyValidUntil(LocalDateTime value) {
        set(21, value);
    }

    /**
     * Getter for <code>nw.contract.report_act_signer_doc_power_of_attorney_valid_until</code>.
     */
    public LocalDateTime getReportActSignerDocPowerOfAttorneyValidUntil() {
        return (LocalDateTime) get(21);
    }

    /**
     * Setter for <code>nw.contract.contractor_id</code>.
     */
    public void setContractorId(String value) {
        set(22, value);
    }

    /**
     * Getter for <code>nw.contract.contractor_id</code>.
     */
    public String getContractorId() {
        return (String) get(22);
    }

    /**
     * Setter for <code>nw.contract.wtime</code>.
     */
    public void setWtime(LocalDateTime value) {
        set(23, value);
    }

    /**
     * Getter for <code>nw.contract.wtime</code>.
     */
    public LocalDateTime getWtime() {
        return (LocalDateTime) get(23);
    }

    /**
     * Setter for <code>nw.contract.current</code>.
     */
    public void setCurrent(Boolean value) {
        set(24, value);
    }

    /**
     * Getter for <code>nw.contract.current</code>.
     */
    public Boolean getCurrent() {
        return (Boolean) get(24);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ContractRecord
     */
    public ContractRecord() {
        super(Contract.CONTRACT);
    }

    /**
     * Create a detached, initialised ContractRecord
     */
    public ContractRecord(Long id, Long eventId, LocalDateTime eventCreatedAt, String contractId, String partyId, Integer paymentInstitutionId, LocalDateTime createdAt, LocalDateTime validSince, LocalDateTime validUntil, ContractStatus status, LocalDateTime statusTerminatedAt, Integer termsId, LocalDateTime legalAgreementSignedAt, String legalAgreementId, LocalDateTime legalAgreementValidUntil, Integer reportActScheduleId, String reportActSignerPosition, String reportActSignerFullName, RepresentativeDocument reportActSignerDocument, LocalDateTime reportActSignerDocPowerOfAttorneySignedAt, String reportActSignerDocPowerOfAttorneyLegalAgreementId, LocalDateTime reportActSignerDocPowerOfAttorneyValidUntil, String contractorId, LocalDateTime wtime, Boolean current) {
        super(Contract.CONTRACT);

        set(0, id);
        set(1, eventId);
        set(2, eventCreatedAt);
        set(3, contractId);
        set(4, partyId);
        set(5, paymentInstitutionId);
        set(6, createdAt);
        set(7, validSince);
        set(8, validUntil);
        set(9, status);
        set(10, statusTerminatedAt);
        set(11, termsId);
        set(12, legalAgreementSignedAt);
        set(13, legalAgreementId);
        set(14, legalAgreementValidUntil);
        set(15, reportActScheduleId);
        set(16, reportActSignerPosition);
        set(17, reportActSignerFullName);
        set(18, reportActSignerDocument);
        set(19, reportActSignerDocPowerOfAttorneySignedAt);
        set(20, reportActSignerDocPowerOfAttorneyLegalAgreementId);
        set(21, reportActSignerDocPowerOfAttorneyValidUntil);
        set(22, contractorId);
        set(23, wtime);
        set(24, current);
    }
}
