/*
 * This file is generated by jOOQ.
*/
package com.rbkmoney.newway.domain.tables.records;


import com.rbkmoney.newway.domain.enums.ContractorType;
import com.rbkmoney.newway.domain.enums.LegalEntity;
import com.rbkmoney.newway.domain.enums.PrivateEntity;
import com.rbkmoney.newway.domain.tables.Contractor;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContractorRecord extends UpdatableRecordImpl<ContractorRecord> {

    private static final long serialVersionUID = -349308071;

    /**
     * Setter for <code>nw.contractor.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>nw.contractor.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>nw.contractor.event_id</code>.
     */
    public void setEventId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>nw.contractor.event_id</code>.
     */
    public Long getEventId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>nw.contractor.event_created_at</code>.
     */
    public void setEventCreatedAt(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>nw.contractor.event_created_at</code>.
     */
    public LocalDateTime getEventCreatedAt() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>nw.contractor.party_id</code>.
     */
    public void setPartyId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>nw.contractor.party_id</code>.
     */
    public String getPartyId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>nw.contractor.contractor_id</code>.
     */
    public void setContractorId(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>nw.contractor.contractor_id</code>.
     */
    public String getContractorId() {
        return (String) get(4);
    }

    /**
     * Setter for <code>nw.contractor.type</code>.
     */
    public void setType(ContractorType value) {
        set(5, value);
    }

    /**
     * Getter for <code>nw.contractor.type</code>.
     */
    public ContractorType getType() {
        return (ContractorType) get(5);
    }

    /**
     * Setter for <code>nw.contractor.identificational_level</code>.
     */
    public void setIdentificationalLevel(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>nw.contractor.identificational_level</code>.
     */
    public String getIdentificationalLevel() {
        return (String) get(6);
    }

    /**
     * Setter for <code>nw.contractor.registered_user_email</code>.
     */
    public void setRegisteredUserEmail(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>nw.contractor.registered_user_email</code>.
     */
    public String getRegisteredUserEmail() {
        return (String) get(7);
    }

    /**
     * Setter for <code>nw.contractor.legal_entity</code>.
     */
    public void setLegalEntity(LegalEntity value) {
        set(8, value);
    }

    /**
     * Getter for <code>nw.contractor.legal_entity</code>.
     */
    public LegalEntity getLegalEntity() {
        return (LegalEntity) get(8);
    }

    /**
     * Setter for <code>nw.contractor.russian_legal_entity_registered_name</code>.
     */
    public void setRussianLegalEntityRegisteredName(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>nw.contractor.russian_legal_entity_registered_name</code>.
     */
    public String getRussianLegalEntityRegisteredName() {
        return (String) get(9);
    }

    /**
     * Setter for <code>nw.contractor.russian_legal_entity_registered_number</code>.
     */
    public void setRussianLegalEntityRegisteredNumber(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>nw.contractor.russian_legal_entity_registered_number</code>.
     */
    public String getRussianLegalEntityRegisteredNumber() {
        return (String) get(10);
    }

    /**
     * Setter for <code>nw.contractor.russian_legal_entity_inn</code>.
     */
    public void setRussianLegalEntityInn(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>nw.contractor.russian_legal_entity_inn</code>.
     */
    public String getRussianLegalEntityInn() {
        return (String) get(11);
    }

    /**
     * Setter for <code>nw.contractor.russian_legal_entity_actual_address</code>.
     */
    public void setRussianLegalEntityActualAddress(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>nw.contractor.russian_legal_entity_actual_address</code>.
     */
    public String getRussianLegalEntityActualAddress() {
        return (String) get(12);
    }

    /**
     * Setter for <code>nw.contractor.russian_legal_entity_post_address</code>.
     */
    public void setRussianLegalEntityPostAddress(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>nw.contractor.russian_legal_entity_post_address</code>.
     */
    public String getRussianLegalEntityPostAddress() {
        return (String) get(13);
    }

    /**
     * Setter for <code>nw.contractor.russian_legal_entity_representative_position</code>.
     */
    public void setRussianLegalEntityRepresentativePosition(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>nw.contractor.russian_legal_entity_representative_position</code>.
     */
    public String getRussianLegalEntityRepresentativePosition() {
        return (String) get(14);
    }

    /**
     * Setter for <code>nw.contractor.russian_legal_entity_representative_full_name</code>.
     */
    public void setRussianLegalEntityRepresentativeFullName(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>nw.contractor.russian_legal_entity_representative_full_name</code>.
     */
    public String getRussianLegalEntityRepresentativeFullName() {
        return (String) get(15);
    }

    /**
     * Setter for <code>nw.contractor.russian_legal_entity_representative_document</code>.
     */
    public void setRussianLegalEntityRepresentativeDocument(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>nw.contractor.russian_legal_entity_representative_document</code>.
     */
    public String getRussianLegalEntityRepresentativeDocument() {
        return (String) get(16);
    }

    /**
     * Setter for <code>nw.contractor.russian_legal_entity_russian_bank_account</code>.
     */
    public void setRussianLegalEntityRussianBankAccount(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>nw.contractor.russian_legal_entity_russian_bank_account</code>.
     */
    public String getRussianLegalEntityRussianBankAccount() {
        return (String) get(17);
    }

    /**
     * Setter for <code>nw.contractor.russian_legal_entity_russian_bank_name</code>.
     */
    public void setRussianLegalEntityRussianBankName(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>nw.contractor.russian_legal_entity_russian_bank_name</code>.
     */
    public String getRussianLegalEntityRussianBankName() {
        return (String) get(18);
    }

    /**
     * Setter for <code>nw.contractor.russian_legal_entity_russian_bank_post_account</code>.
     */
    public void setRussianLegalEntityRussianBankPostAccount(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>nw.contractor.russian_legal_entity_russian_bank_post_account</code>.
     */
    public String getRussianLegalEntityRussianBankPostAccount() {
        return (String) get(19);
    }

    /**
     * Setter for <code>nw.contractor.russian_legal_entity_russian_bank_bik</code>.
     */
    public void setRussianLegalEntityRussianBankBik(String value) {
        set(20, value);
    }

    /**
     * Getter for <code>nw.contractor.russian_legal_entity_russian_bank_bik</code>.
     */
    public String getRussianLegalEntityRussianBankBik() {
        return (String) get(20);
    }

    /**
     * Setter for <code>nw.contractor.international_legal_entity_legal_name</code>.
     */
    public void setInternationalLegalEntityLegalName(String value) {
        set(21, value);
    }

    /**
     * Getter for <code>nw.contractor.international_legal_entity_legal_name</code>.
     */
    public String getInternationalLegalEntityLegalName() {
        return (String) get(21);
    }

    /**
     * Setter for <code>nw.contractor.international_legal_entity_trading_name</code>.
     */
    public void setInternationalLegalEntityTradingName(String value) {
        set(22, value);
    }

    /**
     * Getter for <code>nw.contractor.international_legal_entity_trading_name</code>.
     */
    public String getInternationalLegalEntityTradingName() {
        return (String) get(22);
    }

    /**
     * Setter for <code>nw.contractor.international_legal_entity_registered_address</code>.
     */
    public void setInternationalLegalEntityRegisteredAddress(String value) {
        set(23, value);
    }

    /**
     * Getter for <code>nw.contractor.international_legal_entity_registered_address</code>.
     */
    public String getInternationalLegalEntityRegisteredAddress() {
        return (String) get(23);
    }

    /**
     * Setter for <code>nw.contractor.international_legal_entity_actual_address</code>.
     */
    public void setInternationalLegalEntityActualAddress(String value) {
        set(24, value);
    }

    /**
     * Getter for <code>nw.contractor.international_legal_entity_actual_address</code>.
     */
    public String getInternationalLegalEntityActualAddress() {
        return (String) get(24);
    }

    /**
     * Setter for <code>nw.contractor.international_legal_entity_registered_number</code>.
     */
    public void setInternationalLegalEntityRegisteredNumber(String value) {
        set(25, value);
    }

    /**
     * Getter for <code>nw.contractor.international_legal_entity_registered_number</code>.
     */
    public String getInternationalLegalEntityRegisteredNumber() {
        return (String) get(25);
    }

    /**
     * Setter for <code>nw.contractor.private_entity</code>.
     */
    public void setPrivateEntity(PrivateEntity value) {
        set(26, value);
    }

    /**
     * Getter for <code>nw.contractor.private_entity</code>.
     */
    public PrivateEntity getPrivateEntity() {
        return (PrivateEntity) get(26);
    }

    /**
     * Setter for <code>nw.contractor.russian_private_entity_first_name</code>.
     */
    public void setRussianPrivateEntityFirstName(String value) {
        set(27, value);
    }

    /**
     * Getter for <code>nw.contractor.russian_private_entity_first_name</code>.
     */
    public String getRussianPrivateEntityFirstName() {
        return (String) get(27);
    }

    /**
     * Setter for <code>nw.contractor.russian_private_entity_second_name</code>.
     */
    public void setRussianPrivateEntitySecondName(String value) {
        set(28, value);
    }

    /**
     * Getter for <code>nw.contractor.russian_private_entity_second_name</code>.
     */
    public String getRussianPrivateEntitySecondName() {
        return (String) get(28);
    }

    /**
     * Setter for <code>nw.contractor.russian_private_entity_middle_name</code>.
     */
    public void setRussianPrivateEntityMiddleName(String value) {
        set(29, value);
    }

    /**
     * Getter for <code>nw.contractor.russian_private_entity_middle_name</code>.
     */
    public String getRussianPrivateEntityMiddleName() {
        return (String) get(29);
    }

    /**
     * Setter for <code>nw.contractor.russian_private_entity_phone_number</code>.
     */
    public void setRussianPrivateEntityPhoneNumber(String value) {
        set(30, value);
    }

    /**
     * Getter for <code>nw.contractor.russian_private_entity_phone_number</code>.
     */
    public String getRussianPrivateEntityPhoneNumber() {
        return (String) get(30);
    }

    /**
     * Setter for <code>nw.contractor.russian_private_entity_email</code>.
     */
    public void setRussianPrivateEntityEmail(String value) {
        set(31, value);
    }

    /**
     * Getter for <code>nw.contractor.russian_private_entity_email</code>.
     */
    public String getRussianPrivateEntityEmail() {
        return (String) get(31);
    }

    /**
     * Setter for <code>nw.contractor.wtime</code>.
     */
    public void setWtime(LocalDateTime value) {
        set(32, value);
    }

    /**
     * Getter for <code>nw.contractor.wtime</code>.
     */
    public LocalDateTime getWtime() {
        return (LocalDateTime) get(32);
    }

    /**
     * Setter for <code>nw.contractor.current</code>.
     */
    public void setCurrent(Boolean value) {
        set(33, value);
    }

    /**
     * Getter for <code>nw.contractor.current</code>.
     */
    public Boolean getCurrent() {
        return (Boolean) get(33);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ContractorRecord
     */
    public ContractorRecord() {
        super(Contractor.CONTRACTOR);
    }

    /**
     * Create a detached, initialised ContractorRecord
     */
    public ContractorRecord(Long id, Long eventId, LocalDateTime eventCreatedAt, String partyId, String contractorId, ContractorType type, String identificationalLevel, String registeredUserEmail, LegalEntity legalEntity, String russianLegalEntityRegisteredName, String russianLegalEntityRegisteredNumber, String russianLegalEntityInn, String russianLegalEntityActualAddress, String russianLegalEntityPostAddress, String russianLegalEntityRepresentativePosition, String russianLegalEntityRepresentativeFullName, String russianLegalEntityRepresentativeDocument, String russianLegalEntityRussianBankAccount, String russianLegalEntityRussianBankName, String russianLegalEntityRussianBankPostAccount, String russianLegalEntityRussianBankBik, String internationalLegalEntityLegalName, String internationalLegalEntityTradingName, String internationalLegalEntityRegisteredAddress, String internationalLegalEntityActualAddress, String internationalLegalEntityRegisteredNumber, PrivateEntity privateEntity, String russianPrivateEntityFirstName, String russianPrivateEntitySecondName, String russianPrivateEntityMiddleName, String russianPrivateEntityPhoneNumber, String russianPrivateEntityEmail, LocalDateTime wtime, Boolean current) {
        super(Contractor.CONTRACTOR);

        set(0, id);
        set(1, eventId);
        set(2, eventCreatedAt);
        set(3, partyId);
        set(4, contractorId);
        set(5, type);
        set(6, identificationalLevel);
        set(7, registeredUserEmail);
        set(8, legalEntity);
        set(9, russianLegalEntityRegisteredName);
        set(10, russianLegalEntityRegisteredNumber);
        set(11, russianLegalEntityInn);
        set(12, russianLegalEntityActualAddress);
        set(13, russianLegalEntityPostAddress);
        set(14, russianLegalEntityRepresentativePosition);
        set(15, russianLegalEntityRepresentativeFullName);
        set(16, russianLegalEntityRepresentativeDocument);
        set(17, russianLegalEntityRussianBankAccount);
        set(18, russianLegalEntityRussianBankName);
        set(19, russianLegalEntityRussianBankPostAccount);
        set(20, russianLegalEntityRussianBankBik);
        set(21, internationalLegalEntityLegalName);
        set(22, internationalLegalEntityTradingName);
        set(23, internationalLegalEntityRegisteredAddress);
        set(24, internationalLegalEntityActualAddress);
        set(25, internationalLegalEntityRegisteredNumber);
        set(26, privateEntity);
        set(27, russianPrivateEntityFirstName);
        set(28, russianPrivateEntitySecondName);
        set(29, russianPrivateEntityMiddleName);
        set(30, russianPrivateEntityPhoneNumber);
        set(31, russianPrivateEntityEmail);
        set(32, wtime);
        set(33, current);
    }
}
