/*
 * This file is generated by jOOQ.
 */
package com.rbkmoney.newway.domain.tables.records;


import com.rbkmoney.newway.domain.tables.ContractAdjustment;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContractAdjustmentRecord extends UpdatableRecordImpl<ContractAdjustmentRecord> implements Record7<Long, Long, String, LocalDateTime, LocalDateTime, LocalDateTime, Integer> {

    private static final long serialVersionUID = 1195354317;

    /**
     * Setter for <code>nw.contract_adjustment.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>nw.contract_adjustment.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>nw.contract_adjustment.cntrct_id</code>.
     */
    public void setCntrctId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>nw.contract_adjustment.cntrct_id</code>.
     */
    public Long getCntrctId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>nw.contract_adjustment.contract_adjustment_id</code>.
     */
    public void setContractAdjustmentId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>nw.contract_adjustment.contract_adjustment_id</code>.
     */
    public String getContractAdjustmentId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>nw.contract_adjustment.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>nw.contract_adjustment.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>nw.contract_adjustment.valid_since</code>.
     */
    public void setValidSince(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>nw.contract_adjustment.valid_since</code>.
     */
    public LocalDateTime getValidSince() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>nw.contract_adjustment.valid_until</code>.
     */
    public void setValidUntil(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>nw.contract_adjustment.valid_until</code>.
     */
    public LocalDateTime getValidUntil() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>nw.contract_adjustment.terms_id</code>.
     */
    public void setTermsId(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>nw.contract_adjustment.terms_id</code>.
     */
    public Integer getTermsId() {
        return (Integer) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Long, Long, String, LocalDateTime, LocalDateTime, LocalDateTime, Integer> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Long, Long, String, LocalDateTime, LocalDateTime, LocalDateTime, Integer> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return ContractAdjustment.CONTRACT_ADJUSTMENT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return ContractAdjustment.CONTRACT_ADJUSTMENT.CNTRCT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return ContractAdjustment.CONTRACT_ADJUSTMENT.CONTRACT_ADJUSTMENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field4() {
        return ContractAdjustment.CONTRACT_ADJUSTMENT.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field5() {
        return ContractAdjustment.CONTRACT_ADJUSTMENT.VALID_SINCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field6() {
        return ContractAdjustment.CONTRACT_ADJUSTMENT.VALID_UNTIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return ContractAdjustment.CONTRACT_ADJUSTMENT.TERMS_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getCntrctId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getContractAdjustmentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component4() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component5() {
        return getValidSince();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component6() {
        return getValidUntil();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component7() {
        return getTermsId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getCntrctId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getContractAdjustmentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value4() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value5() {
        return getValidSince();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value6() {
        return getValidUntil();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getTermsId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractAdjustmentRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractAdjustmentRecord value2(Long value) {
        setCntrctId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractAdjustmentRecord value3(String value) {
        setContractAdjustmentId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractAdjustmentRecord value4(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractAdjustmentRecord value5(LocalDateTime value) {
        setValidSince(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractAdjustmentRecord value6(LocalDateTime value) {
        setValidUntil(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractAdjustmentRecord value7(Integer value) {
        setTermsId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractAdjustmentRecord values(Long value1, Long value2, String value3, LocalDateTime value4, LocalDateTime value5, LocalDateTime value6, Integer value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ContractAdjustmentRecord
     */
    public ContractAdjustmentRecord() {
        super(ContractAdjustment.CONTRACT_ADJUSTMENT);
    }

    /**
     * Create a detached, initialised ContractAdjustmentRecord
     */
    public ContractAdjustmentRecord(Long id, Long cntrctId, String contractAdjustmentId, LocalDateTime createdAt, LocalDateTime validSince, LocalDateTime validUntil, Integer termsId) {
        super(ContractAdjustment.CONTRACT_ADJUSTMENT);

        set(0, id);
        set(1, cntrctId);
        set(2, contractAdjustmentId);
        set(3, createdAt);
        set(4, validSince);
        set(5, validUntil);
        set(6, termsId);
    }
}
