/*
 * This file is generated by jOOQ.
*/
package com.rbkmoney.newway.domain.tables.records;


import com.rbkmoney.newway.domain.enums.RefundStatus;
import com.rbkmoney.newway.domain.tables.Refund;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RefundRecord extends UpdatableRecordImpl<RefundRecord> {

    private static final long serialVersionUID = -1657787982;

    /**
     * Setter for <code>nw.refund.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>nw.refund.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>nw.refund.event_id</code>.
     */
    public void setEventId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>nw.refund.event_id</code>.
     */
    public Long getEventId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>nw.refund.event_created_at</code>.
     */
    public void setEventCreatedAt(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>nw.refund.event_created_at</code>.
     */
    public LocalDateTime getEventCreatedAt() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>nw.refund.domain_revision</code>.
     */
    public void setDomainRevision(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>nw.refund.domain_revision</code>.
     */
    public Long getDomainRevision() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>nw.refund.refund_id</code>.
     */
    public void setRefundId(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>nw.refund.refund_id</code>.
     */
    public String getRefundId() {
        return (String) get(4);
    }

    /**
     * Setter for <code>nw.refund.payment_id</code>.
     */
    public void setPaymentId(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>nw.refund.payment_id</code>.
     */
    public String getPaymentId() {
        return (String) get(5);
    }

    /**
     * Setter for <code>nw.refund.invoice_id</code>.
     */
    public void setInvoiceId(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>nw.refund.invoice_id</code>.
     */
    public String getInvoiceId() {
        return (String) get(6);
    }

    /**
     * Setter for <code>nw.refund.party_id</code>.
     */
    public void setPartyId(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>nw.refund.party_id</code>.
     */
    public String getPartyId() {
        return (String) get(7);
    }

    /**
     * Setter for <code>nw.refund.shop_id</code>.
     */
    public void setShopId(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>nw.refund.shop_id</code>.
     */
    public String getShopId() {
        return (String) get(8);
    }

    /**
     * Setter for <code>nw.refund.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>nw.refund.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(9);
    }

    /**
     * Setter for <code>nw.refund.status</code>.
     */
    public void setStatus(RefundStatus value) {
        set(10, value);
    }

    /**
     * Getter for <code>nw.refund.status</code>.
     */
    public RefundStatus getStatus() {
        return (RefundStatus) get(10);
    }

    /**
     * Setter for <code>nw.refund.status_failed_failure</code>.
     */
    public void setStatusFailedFailure(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>nw.refund.status_failed_failure</code>.
     */
    public String getStatusFailedFailure() {
        return (String) get(11);
    }

    /**
     * Setter for <code>nw.refund.amount</code>.
     */
    public void setAmount(Long value) {
        set(12, value);
    }

    /**
     * Getter for <code>nw.refund.amount</code>.
     */
    public Long getAmount() {
        return (Long) get(12);
    }

    /**
     * Setter for <code>nw.refund.currency_code</code>.
     */
    public void setCurrencyCode(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>nw.refund.currency_code</code>.
     */
    public String getCurrencyCode() {
        return (String) get(13);
    }

    /**
     * Setter for <code>nw.refund.reason</code>.
     */
    public void setReason(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>nw.refund.reason</code>.
     */
    public String getReason() {
        return (String) get(14);
    }

    /**
     * Setter for <code>nw.refund.wtime</code>.
     */
    public void setWtime(LocalDateTime value) {
        set(15, value);
    }

    /**
     * Getter for <code>nw.refund.wtime</code>.
     */
    public LocalDateTime getWtime() {
        return (LocalDateTime) get(15);
    }

    /**
     * Setter for <code>nw.refund.current</code>.
     */
    public void setCurrent(Boolean value) {
        set(16, value);
    }

    /**
     * Getter for <code>nw.refund.current</code>.
     */
    public Boolean getCurrent() {
        return (Boolean) get(16);
    }

    /**
     * Setter for <code>nw.refund.session_payload_transaction_bound_trx_id</code>.
     */
    public void setSessionPayloadTransactionBoundTrxId(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>nw.refund.session_payload_transaction_bound_trx_id</code>.
     */
    public String getSessionPayloadTransactionBoundTrxId() {
        return (String) get(17);
    }

    /**
     * Setter for <code>nw.refund.session_payload_transaction_bound_trx_extra_json</code>.
     */
    public void setSessionPayloadTransactionBoundTrxExtraJson(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>nw.refund.session_payload_transaction_bound_trx_extra_json</code>.
     */
    public String getSessionPayloadTransactionBoundTrxExtraJson() {
        return (String) get(18);
    }

    /**
     * Setter for <code>nw.refund.fee</code>.
     */
    public void setFee(Long value) {
        set(19, value);
    }

    /**
     * Getter for <code>nw.refund.fee</code>.
     */
    public Long getFee() {
        return (Long) get(19);
    }

    /**
     * Setter for <code>nw.refund.provider_fee</code>.
     */
    public void setProviderFee(Long value) {
        set(20, value);
    }

    /**
     * Getter for <code>nw.refund.provider_fee</code>.
     */
    public Long getProviderFee() {
        return (Long) get(20);
    }

    /**
     * Setter for <code>nw.refund.external_fee</code>.
     */
    public void setExternalFee(Long value) {
        set(21, value);
    }

    /**
     * Getter for <code>nw.refund.external_fee</code>.
     */
    public Long getExternalFee() {
        return (Long) get(21);
    }

    /**
     * Setter for <code>nw.refund.party_revision</code>.
     */
    public void setPartyRevision(Long value) {
        set(22, value);
    }

    /**
     * Getter for <code>nw.refund.party_revision</code>.
     */
    public Long getPartyRevision() {
        return (Long) get(22);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RefundRecord
     */
    public RefundRecord() {
        super(Refund.REFUND);
    }

    /**
     * Create a detached, initialised RefundRecord
     */
    public RefundRecord(Long id, Long eventId, LocalDateTime eventCreatedAt, Long domainRevision, String refundId, String paymentId, String invoiceId, String partyId, String shopId, LocalDateTime createdAt, RefundStatus status, String statusFailedFailure, Long amount, String currencyCode, String reason, LocalDateTime wtime, Boolean current, String sessionPayloadTransactionBoundTrxId, String sessionPayloadTransactionBoundTrxExtraJson, Long fee, Long providerFee, Long externalFee, Long partyRevision) {
        super(Refund.REFUND);

        set(0, id);
        set(1, eventId);
        set(2, eventCreatedAt);
        set(3, domainRevision);
        set(4, refundId);
        set(5, paymentId);
        set(6, invoiceId);
        set(7, partyId);
        set(8, shopId);
        set(9, createdAt);
        set(10, status);
        set(11, statusFailedFailure);
        set(12, amount);
        set(13, currencyCode);
        set(14, reason);
        set(15, wtime);
        set(16, current);
        set(17, sessionPayloadTransactionBoundTrxId);
        set(18, sessionPayloadTransactionBoundTrxExtraJson);
        set(19, fee);
        set(20, providerFee);
        set(21, externalFee);
        set(22, partyRevision);
    }
}
