/*
 * This file is generated by jOOQ.
*/
package com.rbkmoney.newway.domain.tables.records;


import com.rbkmoney.newway.domain.tables.TermSetHierarchy;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TermSetHierarchyRecord extends UpdatableRecordImpl<TermSetHierarchyRecord> implements Record9<Long, Long, Integer, String, String, Integer, String, LocalDateTime, Boolean> {

    private static final long serialVersionUID = -431717923;

    /**
     * Setter for <code>nw.term_set_hierarchy.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>nw.term_set_hierarchy.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>nw.term_set_hierarchy.version_id</code>.
     */
    public void setVersionId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>nw.term_set_hierarchy.version_id</code>.
     */
    public Long getVersionId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>nw.term_set_hierarchy.term_set_hierarchy_ref_id</code>.
     */
    public void setTermSetHierarchyRefId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>nw.term_set_hierarchy.term_set_hierarchy_ref_id</code>.
     */
    public Integer getTermSetHierarchyRefId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>nw.term_set_hierarchy.name</code>.
     */
    public void setName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>nw.term_set_hierarchy.name</code>.
     */
    public String getName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>nw.term_set_hierarchy.description</code>.
     */
    public void setDescription(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>nw.term_set_hierarchy.description</code>.
     */
    public String getDescription() {
        return (String) get(4);
    }

    /**
     * Setter for <code>nw.term_set_hierarchy.parent_terms_ref_id</code>.
     */
    public void setParentTermsRefId(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>nw.term_set_hierarchy.parent_terms_ref_id</code>.
     */
    public Integer getParentTermsRefId() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>nw.term_set_hierarchy.term_sets_json</code>.
     */
    public void setTermSetsJson(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>nw.term_set_hierarchy.term_sets_json</code>.
     */
    public String getTermSetsJson() {
        return (String) get(6);
    }

    /**
     * Setter for <code>nw.term_set_hierarchy.wtime</code>.
     */
    public void setWtime(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>nw.term_set_hierarchy.wtime</code>.
     */
    public LocalDateTime getWtime() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>nw.term_set_hierarchy.current</code>.
     */
    public void setCurrent(Boolean value) {
        set(8, value);
    }

    /**
     * Getter for <code>nw.term_set_hierarchy.current</code>.
     */
    public Boolean getCurrent() {
        return (Boolean) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Long, Long, Integer, String, String, Integer, String, LocalDateTime, Boolean> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Long, Long, Integer, String, String, Integer, String, LocalDateTime, Boolean> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return TermSetHierarchy.TERM_SET_HIERARCHY.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return TermSetHierarchy.TERM_SET_HIERARCHY.VERSION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return TermSetHierarchy.TERM_SET_HIERARCHY.TERM_SET_HIERARCHY_REF_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TermSetHierarchy.TERM_SET_HIERARCHY.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return TermSetHierarchy.TERM_SET_HIERARCHY.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return TermSetHierarchy.TERM_SET_HIERARCHY.PARENT_TERMS_REF_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return TermSetHierarchy.TERM_SET_HIERARCHY.TERM_SETS_JSON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field8() {
        return TermSetHierarchy.TERM_SET_HIERARCHY.WTIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field9() {
        return TermSetHierarchy.TERM_SET_HIERARCHY.CURRENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getVersionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getTermSetHierarchyRefId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getParentTermsRefId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getTermSetsJson();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value8() {
        return getWtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value9() {
        return getCurrent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TermSetHierarchyRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TermSetHierarchyRecord value2(Long value) {
        setVersionId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TermSetHierarchyRecord value3(Integer value) {
        setTermSetHierarchyRefId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TermSetHierarchyRecord value4(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TermSetHierarchyRecord value5(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TermSetHierarchyRecord value6(Integer value) {
        setParentTermsRefId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TermSetHierarchyRecord value7(String value) {
        setTermSetsJson(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TermSetHierarchyRecord value8(LocalDateTime value) {
        setWtime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TermSetHierarchyRecord value9(Boolean value) {
        setCurrent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TermSetHierarchyRecord values(Long value1, Long value2, Integer value3, String value4, String value5, Integer value6, String value7, LocalDateTime value8, Boolean value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TermSetHierarchyRecord
     */
    public TermSetHierarchyRecord() {
        super(TermSetHierarchy.TERM_SET_HIERARCHY);
    }

    /**
     * Create a detached, initialised TermSetHierarchyRecord
     */
    public TermSetHierarchyRecord(Long id, Long versionId, Integer termSetHierarchyRefId, String name, String description, Integer parentTermsRefId, String termSetsJson, LocalDateTime wtime, Boolean current) {
        super(TermSetHierarchy.TERM_SET_HIERARCHY);

        set(0, id);
        set(1, versionId);
        set(2, termSetHierarchyRefId);
        set(3, name);
        set(4, description);
        set(5, parentTermsRefId);
        set(6, termSetsJson);
        set(7, wtime);
        set(8, current);
    }
}
