/*
 * This file is generated by jOOQ.
*/
package com.rbkmoney.newway.domain.tables;


import com.rbkmoney.newway.domain.Keys;
import com.rbkmoney.newway.domain.Nw;
import com.rbkmoney.newway.domain.enums.AdjustmentStatus;
import com.rbkmoney.newway.domain.tables.records.AdjustmentRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Adjustment extends TableImpl<AdjustmentRecord> {

    private static final long serialVersionUID = 1192366780;

    /**
     * The reference instance of <code>nw.adjustment</code>
     */
    public static final Adjustment ADJUSTMENT = new Adjustment();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AdjustmentRecord> getRecordType() {
        return AdjustmentRecord.class;
    }

    /**
     * The column <code>nw.adjustment.id</code>.
     */
    public final TableField<AdjustmentRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('nw.adjustment_id_seq'::regclass)", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>nw.adjustment.event_id</code>.
     */
    public final TableField<AdjustmentRecord, Long> EVENT_ID = createField("event_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>nw.adjustment.event_created_at</code>.
     */
    public final TableField<AdjustmentRecord, LocalDateTime> EVENT_CREATED_AT = createField("event_created_at", org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false), this, "");

    /**
     * The column <code>nw.adjustment.domain_revision</code>.
     */
    public final TableField<AdjustmentRecord, Long> DOMAIN_REVISION = createField("domain_revision", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>nw.adjustment.adjustment_id</code>.
     */
    public final TableField<AdjustmentRecord, String> ADJUSTMENT_ID = createField("adjustment_id", org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>nw.adjustment.payment_id</code>.
     */
    public final TableField<AdjustmentRecord, String> PAYMENT_ID = createField("payment_id", org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>nw.adjustment.invoice_id</code>.
     */
    public final TableField<AdjustmentRecord, String> INVOICE_ID = createField("invoice_id", org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>nw.adjustment.party_id</code>.
     */
    public final TableField<AdjustmentRecord, String> PARTY_ID = createField("party_id", org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>nw.adjustment.shop_id</code>.
     */
    public final TableField<AdjustmentRecord, String> SHOP_ID = createField("shop_id", org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>nw.adjustment.created_at</code>.
     */
    public final TableField<AdjustmentRecord, LocalDateTime> CREATED_AT = createField("created_at", org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false), this, "");

    /**
     * The column <code>nw.adjustment.status</code>.
     */
    public final TableField<AdjustmentRecord, AdjustmentStatus> STATUS = createField("status", org.jooq.util.postgres.PostgresDataType.VARCHAR.asEnumDataType(com.rbkmoney.newway.domain.enums.AdjustmentStatus.class), this, "");

    /**
     * The column <code>nw.adjustment.status_captured_at</code>.
     */
    public final TableField<AdjustmentRecord, LocalDateTime> STATUS_CAPTURED_AT = createField("status_captured_at", org.jooq.impl.SQLDataType.LOCALDATETIME, this, "");

    /**
     * The column <code>nw.adjustment.status_cancelled_at</code>.
     */
    public final TableField<AdjustmentRecord, LocalDateTime> STATUS_CANCELLED_AT = createField("status_cancelled_at", org.jooq.impl.SQLDataType.LOCALDATETIME, this, "");

    /**
     * The column <code>nw.adjustment.reason</code>.
     */
    public final TableField<AdjustmentRecord, String> REASON = createField("reason", org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>nw.adjustment.wtime</code>.
     */
    public final TableField<AdjustmentRecord, LocalDateTime> WTIME = createField("wtime", org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(org.jooq.impl.DSL.field("timezone('utc'::text, now())", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>nw.adjustment.current</code>.
     */
    public final TableField<AdjustmentRecord, Boolean> CURRENT = createField("current", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false).defaultValue(org.jooq.impl.DSL.field("true", org.jooq.impl.SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>nw.adjustment.fee</code>.
     */
    public final TableField<AdjustmentRecord, Long> FEE = createField("fee", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>nw.adjustment.provider_fee</code>.
     */
    public final TableField<AdjustmentRecord, Long> PROVIDER_FEE = createField("provider_fee", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>nw.adjustment.external_fee</code>.
     */
    public final TableField<AdjustmentRecord, Long> EXTERNAL_FEE = createField("external_fee", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>nw.adjustment.party_revision</code>.
     */
    public final TableField<AdjustmentRecord, Long> PARTY_REVISION = createField("party_revision", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * Create a <code>nw.adjustment</code> table reference
     */
    public Adjustment() {
        this("adjustment", null);
    }

    /**
     * Create an aliased <code>nw.adjustment</code> table reference
     */
    public Adjustment(String alias) {
        this(alias, ADJUSTMENT);
    }

    private Adjustment(String alias, Table<AdjustmentRecord> aliased) {
        this(alias, aliased, null);
    }

    private Adjustment(String alias, Table<AdjustmentRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Nw.NW;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<AdjustmentRecord, Long> getIdentity() {
        return Keys.IDENTITY_ADJUSTMENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<AdjustmentRecord> getPrimaryKey() {
        return Keys.ADJUSTMENT_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<AdjustmentRecord>> getKeys() {
        return Arrays.<UniqueKey<AdjustmentRecord>>asList(Keys.ADJUSTMENT_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Adjustment as(String alias) {
        return new Adjustment(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Adjustment rename(String name) {
        return new Adjustment(name, null);
    }
}
