/*
 * This file is generated by jOOQ.
*/
package com.rbkmoney.newway.domain.tables;


import com.rbkmoney.newway.domain.Keys;
import com.rbkmoney.newway.domain.Nw;
import com.rbkmoney.newway.domain.tables.records.IdentityRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Identity extends TableImpl<IdentityRecord> {

    private static final long serialVersionUID = -626874437;

    /**
     * The reference instance of <code>nw.identity</code>
     */
    public static final Identity IDENTITY = new Identity();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<IdentityRecord> getRecordType() {
        return IdentityRecord.class;
    }

    /**
     * The column <code>nw.identity.id</code>.
     */
    public final TableField<IdentityRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('nw.identity_id_seq'::regclass)", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>nw.identity.event_id</code>.
     */
    public final TableField<IdentityRecord, Long> EVENT_ID = createField("event_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>nw.identity.event_created_at</code>.
     */
    public final TableField<IdentityRecord, LocalDateTime> EVENT_CREATED_AT = createField("event_created_at", org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false), this, "");

    /**
     * The column <code>nw.identity.event_occured_at</code>.
     */
    public final TableField<IdentityRecord, LocalDateTime> EVENT_OCCURED_AT = createField("event_occured_at", org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false), this, "");

    /**
     * The column <code>nw.identity.sequence_id</code>.
     */
    public final TableField<IdentityRecord, Integer> SEQUENCE_ID = createField("sequence_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>nw.identity.party_id</code>.
     */
    public final TableField<IdentityRecord, String> PARTY_ID = createField("party_id", org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>nw.identity.party_contract_id</code>.
     */
    public final TableField<IdentityRecord, String> PARTY_CONTRACT_ID = createField("party_contract_id", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>nw.identity.identity_id</code>.
     */
    public final TableField<IdentityRecord, String> IDENTITY_ID = createField("identity_id", org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>nw.identity.identity_provider_id</code>.
     */
    public final TableField<IdentityRecord, String> IDENTITY_PROVIDER_ID = createField("identity_provider_id", org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>nw.identity.identity_class_id</code>.
     */
    public final TableField<IdentityRecord, String> IDENTITY_CLASS_ID = createField("identity_class_id", org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>nw.identity.identity_effective_chalenge_id</code>.
     */
    public final TableField<IdentityRecord, String> IDENTITY_EFFECTIVE_CHALENGE_ID = createField("identity_effective_chalenge_id", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>nw.identity.identity_level_id</code>.
     */
    public final TableField<IdentityRecord, String> IDENTITY_LEVEL_ID = createField("identity_level_id", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>nw.identity.wtime</code>.
     */
    public final TableField<IdentityRecord, LocalDateTime> WTIME = createField("wtime", org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(org.jooq.impl.DSL.field("timezone('utc'::text, now())", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>nw.identity.current</code>.
     */
    public final TableField<IdentityRecord, Boolean> CURRENT = createField("current", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false).defaultValue(org.jooq.impl.DSL.field("true", org.jooq.impl.SQLDataType.BOOLEAN)), this, "");

    /**
     * Create a <code>nw.identity</code> table reference
     */
    public Identity() {
        this("identity", null);
    }

    /**
     * Create an aliased <code>nw.identity</code> table reference
     */
    public Identity(String alias) {
        this(alias, IDENTITY);
    }

    private Identity(String alias, Table<IdentityRecord> aliased) {
        this(alias, aliased, null);
    }

    private Identity(String alias, Table<IdentityRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Nw.NW;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public org.jooq.Identity<IdentityRecord, Long> getIdentity() {
        return Keys.IDENTITY_IDENTITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<IdentityRecord> getPrimaryKey() {
        return Keys.IDENTITY_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<IdentityRecord>> getKeys() {
        return Arrays.<UniqueKey<IdentityRecord>>asList(Keys.IDENTITY_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity as(String alias) {
        return new Identity(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Identity rename(String name) {
        return new Identity(name, null);
    }
}
