/*
 * This file is generated by jOOQ.
*/
package com.rbkmoney.newway.domain.tables;


import com.rbkmoney.newway.domain.Keys;
import com.rbkmoney.newway.domain.Nw;
import com.rbkmoney.newway.domain.tables.records.PayoutMethodRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PayoutMethod extends TableImpl<PayoutMethodRecord> {

    private static final long serialVersionUID = 1827051660;

    /**
     * The reference instance of <code>nw.payout_method</code>
     */
    public static final PayoutMethod PAYOUT_METHOD = new PayoutMethod();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PayoutMethodRecord> getRecordType() {
        return PayoutMethodRecord.class;
    }

    /**
     * The column <code>nw.payout_method.id</code>.
     */
    public final TableField<PayoutMethodRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('nw.payout_method_id_seq'::regclass)", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>nw.payout_method.version_id</code>.
     */
    public final TableField<PayoutMethodRecord, Long> VERSION_ID = createField("version_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>nw.payout_method.payout_method_ref_id</code>.
     */
    public final TableField<PayoutMethodRecord, String> PAYOUT_METHOD_REF_ID = createField("payout_method_ref_id", org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>nw.payout_method.name</code>.
     */
    public final TableField<PayoutMethodRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>nw.payout_method.description</code>.
     */
    public final TableField<PayoutMethodRecord, String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>nw.payout_method.wtime</code>.
     */
    public final TableField<PayoutMethodRecord, LocalDateTime> WTIME = createField("wtime", org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(org.jooq.impl.DSL.field("timezone('utc'::text, now())", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>nw.payout_method.current</code>.
     */
    public final TableField<PayoutMethodRecord, Boolean> CURRENT = createField("current", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false).defaultValue(org.jooq.impl.DSL.field("true", org.jooq.impl.SQLDataType.BOOLEAN)), this, "");

    /**
     * Create a <code>nw.payout_method</code> table reference
     */
    public PayoutMethod() {
        this("payout_method", null);
    }

    /**
     * Create an aliased <code>nw.payout_method</code> table reference
     */
    public PayoutMethod(String alias) {
        this(alias, PAYOUT_METHOD);
    }

    private PayoutMethod(String alias, Table<PayoutMethodRecord> aliased) {
        this(alias, aliased, null);
    }

    private PayoutMethod(String alias, Table<PayoutMethodRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Nw.NW;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<PayoutMethodRecord, Long> getIdentity() {
        return Keys.IDENTITY_PAYOUT_METHOD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<PayoutMethodRecord> getPrimaryKey() {
        return Keys.PAYOUT_METHOD_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<PayoutMethodRecord>> getKeys() {
        return Arrays.<UniqueKey<PayoutMethodRecord>>asList(Keys.PAYOUT_METHOD_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PayoutMethod as(String alias) {
        return new PayoutMethod(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public PayoutMethod rename(String name) {
        return new PayoutMethod(name, null);
    }
}
