/*
 * This file is generated by jOOQ.
*/
package com.rbkmoney.newway.domain.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InvoiceCart implements Serializable {

    private static final long serialVersionUID = 1899038426;

    private Long    id;
    private Long    invId;
    private String  product;
    private Integer quantity;
    private Long    amount;
    private String  currencyCode;
    private String  metadataJson;

    public InvoiceCart() {}

    public InvoiceCart(InvoiceCart value) {
        this.id = value.id;
        this.invId = value.invId;
        this.product = value.product;
        this.quantity = value.quantity;
        this.amount = value.amount;
        this.currencyCode = value.currencyCode;
        this.metadataJson = value.metadataJson;
    }

    public InvoiceCart(
        Long    id,
        Long    invId,
        String  product,
        Integer quantity,
        Long    amount,
        String  currencyCode,
        String  metadataJson
    ) {
        this.id = id;
        this.invId = invId;
        this.product = product;
        this.quantity = quantity;
        this.amount = amount;
        this.currencyCode = currencyCode;
        this.metadataJson = metadataJson;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getInvId() {
        return this.invId;
    }

    public void setInvId(Long invId) {
        this.invId = invId;
    }

    public String getProduct() {
        return this.product;
    }

    public void setProduct(String product) {
        this.product = product;
    }

    public Integer getQuantity() {
        return this.quantity;
    }

    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    public Long getAmount() {
        return this.amount;
    }

    public void setAmount(Long amount) {
        this.amount = amount;
    }

    public String getCurrencyCode() {
        return this.currencyCode;
    }

    public void setCurrencyCode(String currencyCode) {
        this.currencyCode = currencyCode;
    }

    public String getMetadataJson() {
        return this.metadataJson;
    }

    public void setMetadataJson(String metadataJson) {
        this.metadataJson = metadataJson;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final InvoiceCart other = (InvoiceCart) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (invId == null) {
            if (other.invId != null)
                return false;
        }
        else if (!invId.equals(other.invId))
            return false;
        if (product == null) {
            if (other.product != null)
                return false;
        }
        else if (!product.equals(other.product))
            return false;
        if (quantity == null) {
            if (other.quantity != null)
                return false;
        }
        else if (!quantity.equals(other.quantity))
            return false;
        if (amount == null) {
            if (other.amount != null)
                return false;
        }
        else if (!amount.equals(other.amount))
            return false;
        if (currencyCode == null) {
            if (other.currencyCode != null)
                return false;
        }
        else if (!currencyCode.equals(other.currencyCode))
            return false;
        if (metadataJson == null) {
            if (other.metadataJson != null)
                return false;
        }
        else if (!metadataJson.equals(other.metadataJson))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.invId == null) ? 0 : this.invId.hashCode());
        result = prime * result + ((this.product == null) ? 0 : this.product.hashCode());
        result = prime * result + ((this.quantity == null) ? 0 : this.quantity.hashCode());
        result = prime * result + ((this.amount == null) ? 0 : this.amount.hashCode());
        result = prime * result + ((this.currencyCode == null) ? 0 : this.currencyCode.hashCode());
        result = prime * result + ((this.metadataJson == null) ? 0 : this.metadataJson.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("InvoiceCart (");

        sb.append(id);
        sb.append(", ").append(invId);
        sb.append(", ").append(product);
        sb.append(", ").append(quantity);
        sb.append(", ").append(amount);
        sb.append(", ").append(currencyCode);
        sb.append(", ").append(metadataJson);

        sb.append(")");
        return sb.toString();
    }
}
