/*
 * This file is generated by jOOQ.
*/
package com.rbkmoney.newway.domain.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PaymentInstitution implements Serializable {

    private static final long serialVersionUID = -777039423;

    private Long          id;
    private Long          versionId;
    private Integer       paymentInstitutionRefId;
    private String        name;
    private String        description;
    private Integer       calendarRefId;
    private String        systemAccountSetJson;
    private String        defaultContractTemplateJson;
    private String        defaultWalletContractTemplateJson;
    private String        providersJson;
    private String        inspectorJson;
    private String        realm;
    private String        residencesJson;
    private LocalDateTime wtime;
    private Boolean       current;

    public PaymentInstitution() {}

    public PaymentInstitution(PaymentInstitution value) {
        this.id = value.id;
        this.versionId = value.versionId;
        this.paymentInstitutionRefId = value.paymentInstitutionRefId;
        this.name = value.name;
        this.description = value.description;
        this.calendarRefId = value.calendarRefId;
        this.systemAccountSetJson = value.systemAccountSetJson;
        this.defaultContractTemplateJson = value.defaultContractTemplateJson;
        this.defaultWalletContractTemplateJson = value.defaultWalletContractTemplateJson;
        this.providersJson = value.providersJson;
        this.inspectorJson = value.inspectorJson;
        this.realm = value.realm;
        this.residencesJson = value.residencesJson;
        this.wtime = value.wtime;
        this.current = value.current;
    }

    public PaymentInstitution(
        Long          id,
        Long          versionId,
        Integer       paymentInstitutionRefId,
        String        name,
        String        description,
        Integer       calendarRefId,
        String        systemAccountSetJson,
        String        defaultContractTemplateJson,
        String        defaultWalletContractTemplateJson,
        String        providersJson,
        String        inspectorJson,
        String        realm,
        String        residencesJson,
        LocalDateTime wtime,
        Boolean       current
    ) {
        this.id = id;
        this.versionId = versionId;
        this.paymentInstitutionRefId = paymentInstitutionRefId;
        this.name = name;
        this.description = description;
        this.calendarRefId = calendarRefId;
        this.systemAccountSetJson = systemAccountSetJson;
        this.defaultContractTemplateJson = defaultContractTemplateJson;
        this.defaultWalletContractTemplateJson = defaultWalletContractTemplateJson;
        this.providersJson = providersJson;
        this.inspectorJson = inspectorJson;
        this.realm = realm;
        this.residencesJson = residencesJson;
        this.wtime = wtime;
        this.current = current;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getVersionId() {
        return this.versionId;
    }

    public void setVersionId(Long versionId) {
        this.versionId = versionId;
    }

    public Integer getPaymentInstitutionRefId() {
        return this.paymentInstitutionRefId;
    }

    public void setPaymentInstitutionRefId(Integer paymentInstitutionRefId) {
        this.paymentInstitutionRefId = paymentInstitutionRefId;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Integer getCalendarRefId() {
        return this.calendarRefId;
    }

    public void setCalendarRefId(Integer calendarRefId) {
        this.calendarRefId = calendarRefId;
    }

    public String getSystemAccountSetJson() {
        return this.systemAccountSetJson;
    }

    public void setSystemAccountSetJson(String systemAccountSetJson) {
        this.systemAccountSetJson = systemAccountSetJson;
    }

    public String getDefaultContractTemplateJson() {
        return this.defaultContractTemplateJson;
    }

    public void setDefaultContractTemplateJson(String defaultContractTemplateJson) {
        this.defaultContractTemplateJson = defaultContractTemplateJson;
    }

    public String getDefaultWalletContractTemplateJson() {
        return this.defaultWalletContractTemplateJson;
    }

    public void setDefaultWalletContractTemplateJson(String defaultWalletContractTemplateJson) {
        this.defaultWalletContractTemplateJson = defaultWalletContractTemplateJson;
    }

    public String getProvidersJson() {
        return this.providersJson;
    }

    public void setProvidersJson(String providersJson) {
        this.providersJson = providersJson;
    }

    public String getInspectorJson() {
        return this.inspectorJson;
    }

    public void setInspectorJson(String inspectorJson) {
        this.inspectorJson = inspectorJson;
    }

    public String getRealm() {
        return this.realm;
    }

    public void setRealm(String realm) {
        this.realm = realm;
    }

    public String getResidencesJson() {
        return this.residencesJson;
    }

    public void setResidencesJson(String residencesJson) {
        this.residencesJson = residencesJson;
    }

    public LocalDateTime getWtime() {
        return this.wtime;
    }

    public void setWtime(LocalDateTime wtime) {
        this.wtime = wtime;
    }

    public Boolean getCurrent() {
        return this.current;
    }

    public void setCurrent(Boolean current) {
        this.current = current;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final PaymentInstitution other = (PaymentInstitution) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (versionId == null) {
            if (other.versionId != null)
                return false;
        }
        else if (!versionId.equals(other.versionId))
            return false;
        if (paymentInstitutionRefId == null) {
            if (other.paymentInstitutionRefId != null)
                return false;
        }
        else if (!paymentInstitutionRefId.equals(other.paymentInstitutionRefId))
            return false;
        if (name == null) {
            if (other.name != null)
                return false;
        }
        else if (!name.equals(other.name))
            return false;
        if (description == null) {
            if (other.description != null)
                return false;
        }
        else if (!description.equals(other.description))
            return false;
        if (calendarRefId == null) {
            if (other.calendarRefId != null)
                return false;
        }
        else if (!calendarRefId.equals(other.calendarRefId))
            return false;
        if (systemAccountSetJson == null) {
            if (other.systemAccountSetJson != null)
                return false;
        }
        else if (!systemAccountSetJson.equals(other.systemAccountSetJson))
            return false;
        if (defaultContractTemplateJson == null) {
            if (other.defaultContractTemplateJson != null)
                return false;
        }
        else if (!defaultContractTemplateJson.equals(other.defaultContractTemplateJson))
            return false;
        if (defaultWalletContractTemplateJson == null) {
            if (other.defaultWalletContractTemplateJson != null)
                return false;
        }
        else if (!defaultWalletContractTemplateJson.equals(other.defaultWalletContractTemplateJson))
            return false;
        if (providersJson == null) {
            if (other.providersJson != null)
                return false;
        }
        else if (!providersJson.equals(other.providersJson))
            return false;
        if (inspectorJson == null) {
            if (other.inspectorJson != null)
                return false;
        }
        else if (!inspectorJson.equals(other.inspectorJson))
            return false;
        if (realm == null) {
            if (other.realm != null)
                return false;
        }
        else if (!realm.equals(other.realm))
            return false;
        if (residencesJson == null) {
            if (other.residencesJson != null)
                return false;
        }
        else if (!residencesJson.equals(other.residencesJson))
            return false;
        if (wtime == null) {
            if (other.wtime != null)
                return false;
        }
        else if (!wtime.equals(other.wtime))
            return false;
        if (current == null) {
            if (other.current != null)
                return false;
        }
        else if (!current.equals(other.current))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.versionId == null) ? 0 : this.versionId.hashCode());
        result = prime * result + ((this.paymentInstitutionRefId == null) ? 0 : this.paymentInstitutionRefId.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.description == null) ? 0 : this.description.hashCode());
        result = prime * result + ((this.calendarRefId == null) ? 0 : this.calendarRefId.hashCode());
        result = prime * result + ((this.systemAccountSetJson == null) ? 0 : this.systemAccountSetJson.hashCode());
        result = prime * result + ((this.defaultContractTemplateJson == null) ? 0 : this.defaultContractTemplateJson.hashCode());
        result = prime * result + ((this.defaultWalletContractTemplateJson == null) ? 0 : this.defaultWalletContractTemplateJson.hashCode());
        result = prime * result + ((this.providersJson == null) ? 0 : this.providersJson.hashCode());
        result = prime * result + ((this.inspectorJson == null) ? 0 : this.inspectorJson.hashCode());
        result = prime * result + ((this.realm == null) ? 0 : this.realm.hashCode());
        result = prime * result + ((this.residencesJson == null) ? 0 : this.residencesJson.hashCode());
        result = prime * result + ((this.wtime == null) ? 0 : this.wtime.hashCode());
        result = prime * result + ((this.current == null) ? 0 : this.current.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PaymentInstitution (");

        sb.append(id);
        sb.append(", ").append(versionId);
        sb.append(", ").append(paymentInstitutionRefId);
        sb.append(", ").append(name);
        sb.append(", ").append(description);
        sb.append(", ").append(calendarRefId);
        sb.append(", ").append(systemAccountSetJson);
        sb.append(", ").append(defaultContractTemplateJson);
        sb.append(", ").append(defaultWalletContractTemplateJson);
        sb.append(", ").append(providersJson);
        sb.append(", ").append(inspectorJson);
        sb.append(", ").append(realm);
        sb.append(", ").append(residencesJson);
        sb.append(", ").append(wtime);
        sb.append(", ").append(current);

        sb.append(")");
        return sb.toString();
    }
}
