/*
 * This file is generated by jOOQ.
*/
package com.rbkmoney.newway.domain.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Provider implements Serializable {

    private static final long serialVersionUID = -382510950;

    private Long          id;
    private Long          versionId;
    private Integer       providerRefId;
    private String        name;
    private String        description;
    private Integer       proxyRefId;
    private String        proxyAdditionalJson;
    private String        terminalJson;
    private String        absAccount;
    private String        paymentTermsJson;
    private String        recurrentPaytoolTermsJson;
    private String        accountsJson;
    private LocalDateTime wtime;
    private Boolean       current;

    public Provider() {}

    public Provider(Provider value) {
        this.id = value.id;
        this.versionId = value.versionId;
        this.providerRefId = value.providerRefId;
        this.name = value.name;
        this.description = value.description;
        this.proxyRefId = value.proxyRefId;
        this.proxyAdditionalJson = value.proxyAdditionalJson;
        this.terminalJson = value.terminalJson;
        this.absAccount = value.absAccount;
        this.paymentTermsJson = value.paymentTermsJson;
        this.recurrentPaytoolTermsJson = value.recurrentPaytoolTermsJson;
        this.accountsJson = value.accountsJson;
        this.wtime = value.wtime;
        this.current = value.current;
    }

    public Provider(
        Long          id,
        Long          versionId,
        Integer       providerRefId,
        String        name,
        String        description,
        Integer       proxyRefId,
        String        proxyAdditionalJson,
        String        terminalJson,
        String        absAccount,
        String        paymentTermsJson,
        String        recurrentPaytoolTermsJson,
        String        accountsJson,
        LocalDateTime wtime,
        Boolean       current
    ) {
        this.id = id;
        this.versionId = versionId;
        this.providerRefId = providerRefId;
        this.name = name;
        this.description = description;
        this.proxyRefId = proxyRefId;
        this.proxyAdditionalJson = proxyAdditionalJson;
        this.terminalJson = terminalJson;
        this.absAccount = absAccount;
        this.paymentTermsJson = paymentTermsJson;
        this.recurrentPaytoolTermsJson = recurrentPaytoolTermsJson;
        this.accountsJson = accountsJson;
        this.wtime = wtime;
        this.current = current;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getVersionId() {
        return this.versionId;
    }

    public void setVersionId(Long versionId) {
        this.versionId = versionId;
    }

    public Integer getProviderRefId() {
        return this.providerRefId;
    }

    public void setProviderRefId(Integer providerRefId) {
        this.providerRefId = providerRefId;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Integer getProxyRefId() {
        return this.proxyRefId;
    }

    public void setProxyRefId(Integer proxyRefId) {
        this.proxyRefId = proxyRefId;
    }

    public String getProxyAdditionalJson() {
        return this.proxyAdditionalJson;
    }

    public void setProxyAdditionalJson(String proxyAdditionalJson) {
        this.proxyAdditionalJson = proxyAdditionalJson;
    }

    public String getTerminalJson() {
        return this.terminalJson;
    }

    public void setTerminalJson(String terminalJson) {
        this.terminalJson = terminalJson;
    }

    public String getAbsAccount() {
        return this.absAccount;
    }

    public void setAbsAccount(String absAccount) {
        this.absAccount = absAccount;
    }

    public String getPaymentTermsJson() {
        return this.paymentTermsJson;
    }

    public void setPaymentTermsJson(String paymentTermsJson) {
        this.paymentTermsJson = paymentTermsJson;
    }

    public String getRecurrentPaytoolTermsJson() {
        return this.recurrentPaytoolTermsJson;
    }

    public void setRecurrentPaytoolTermsJson(String recurrentPaytoolTermsJson) {
        this.recurrentPaytoolTermsJson = recurrentPaytoolTermsJson;
    }

    public String getAccountsJson() {
        return this.accountsJson;
    }

    public void setAccountsJson(String accountsJson) {
        this.accountsJson = accountsJson;
    }

    public LocalDateTime getWtime() {
        return this.wtime;
    }

    public void setWtime(LocalDateTime wtime) {
        this.wtime = wtime;
    }

    public Boolean getCurrent() {
        return this.current;
    }

    public void setCurrent(Boolean current) {
        this.current = current;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Provider other = (Provider) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (versionId == null) {
            if (other.versionId != null)
                return false;
        }
        else if (!versionId.equals(other.versionId))
            return false;
        if (providerRefId == null) {
            if (other.providerRefId != null)
                return false;
        }
        else if (!providerRefId.equals(other.providerRefId))
            return false;
        if (name == null) {
            if (other.name != null)
                return false;
        }
        else if (!name.equals(other.name))
            return false;
        if (description == null) {
            if (other.description != null)
                return false;
        }
        else if (!description.equals(other.description))
            return false;
        if (proxyRefId == null) {
            if (other.proxyRefId != null)
                return false;
        }
        else if (!proxyRefId.equals(other.proxyRefId))
            return false;
        if (proxyAdditionalJson == null) {
            if (other.proxyAdditionalJson != null)
                return false;
        }
        else if (!proxyAdditionalJson.equals(other.proxyAdditionalJson))
            return false;
        if (terminalJson == null) {
            if (other.terminalJson != null)
                return false;
        }
        else if (!terminalJson.equals(other.terminalJson))
            return false;
        if (absAccount == null) {
            if (other.absAccount != null)
                return false;
        }
        else if (!absAccount.equals(other.absAccount))
            return false;
        if (paymentTermsJson == null) {
            if (other.paymentTermsJson != null)
                return false;
        }
        else if (!paymentTermsJson.equals(other.paymentTermsJson))
            return false;
        if (recurrentPaytoolTermsJson == null) {
            if (other.recurrentPaytoolTermsJson != null)
                return false;
        }
        else if (!recurrentPaytoolTermsJson.equals(other.recurrentPaytoolTermsJson))
            return false;
        if (accountsJson == null) {
            if (other.accountsJson != null)
                return false;
        }
        else if (!accountsJson.equals(other.accountsJson))
            return false;
        if (wtime == null) {
            if (other.wtime != null)
                return false;
        }
        else if (!wtime.equals(other.wtime))
            return false;
        if (current == null) {
            if (other.current != null)
                return false;
        }
        else if (!current.equals(other.current))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.versionId == null) ? 0 : this.versionId.hashCode());
        result = prime * result + ((this.providerRefId == null) ? 0 : this.providerRefId.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.description == null) ? 0 : this.description.hashCode());
        result = prime * result + ((this.proxyRefId == null) ? 0 : this.proxyRefId.hashCode());
        result = prime * result + ((this.proxyAdditionalJson == null) ? 0 : this.proxyAdditionalJson.hashCode());
        result = prime * result + ((this.terminalJson == null) ? 0 : this.terminalJson.hashCode());
        result = prime * result + ((this.absAccount == null) ? 0 : this.absAccount.hashCode());
        result = prime * result + ((this.paymentTermsJson == null) ? 0 : this.paymentTermsJson.hashCode());
        result = prime * result + ((this.recurrentPaytoolTermsJson == null) ? 0 : this.recurrentPaytoolTermsJson.hashCode());
        result = prime * result + ((this.accountsJson == null) ? 0 : this.accountsJson.hashCode());
        result = prime * result + ((this.wtime == null) ? 0 : this.wtime.hashCode());
        result = prime * result + ((this.current == null) ? 0 : this.current.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Provider (");

        sb.append(id);
        sb.append(", ").append(versionId);
        sb.append(", ").append(providerRefId);
        sb.append(", ").append(name);
        sb.append(", ").append(description);
        sb.append(", ").append(proxyRefId);
        sb.append(", ").append(proxyAdditionalJson);
        sb.append(", ").append(terminalJson);
        sb.append(", ").append(absAccount);
        sb.append(", ").append(paymentTermsJson);
        sb.append(", ").append(recurrentPaytoolTermsJson);
        sb.append(", ").append(accountsJson);
        sb.append(", ").append(wtime);
        sb.append(", ").append(current);

        sb.append(")");
        return sb.toString();
    }
}
