/*
 * This file is generated by jOOQ.
*/
package com.rbkmoney.newway.domain.tables.pojos;


import com.rbkmoney.newway.domain.enums.Blocking;
import com.rbkmoney.newway.domain.enums.Suspension;

import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Shop implements Serializable {

    private static final long serialVersionUID = 1108378929;

    private Long          id;
    private Long          eventId;
    private LocalDateTime eventCreatedAt;
    private String        partyId;
    private String        shopId;
    private LocalDateTime createdAt;
    private Blocking      blocking;
    private String        blockingUnblockedReason;
    private LocalDateTime blockingUnblockedSince;
    private String        blockingBlockedReason;
    private LocalDateTime blockingBlockedSince;
    private Suspension    suspension;
    private LocalDateTime suspensionActiveSince;
    private LocalDateTime suspensionSuspendedSince;
    private String        detailsName;
    private String        detailsDescription;
    private String        locationUrl;
    private Integer       categoryId;
    private String        accountCurrencyCode;
    private Long          accountSettlement;
    private Long          accountGuarantee;
    private Long          accountPayout;
    private String        contractId;
    private String        payoutToolId;
    private Integer       payoutScheduleId;
    private LocalDateTime wtime;
    private Boolean       current;
    private Long          revision;

    public Shop() {}

    public Shop(Shop value) {
        this.id = value.id;
        this.eventId = value.eventId;
        this.eventCreatedAt = value.eventCreatedAt;
        this.partyId = value.partyId;
        this.shopId = value.shopId;
        this.createdAt = value.createdAt;
        this.blocking = value.blocking;
        this.blockingUnblockedReason = value.blockingUnblockedReason;
        this.blockingUnblockedSince = value.blockingUnblockedSince;
        this.blockingBlockedReason = value.blockingBlockedReason;
        this.blockingBlockedSince = value.blockingBlockedSince;
        this.suspension = value.suspension;
        this.suspensionActiveSince = value.suspensionActiveSince;
        this.suspensionSuspendedSince = value.suspensionSuspendedSince;
        this.detailsName = value.detailsName;
        this.detailsDescription = value.detailsDescription;
        this.locationUrl = value.locationUrl;
        this.categoryId = value.categoryId;
        this.accountCurrencyCode = value.accountCurrencyCode;
        this.accountSettlement = value.accountSettlement;
        this.accountGuarantee = value.accountGuarantee;
        this.accountPayout = value.accountPayout;
        this.contractId = value.contractId;
        this.payoutToolId = value.payoutToolId;
        this.payoutScheduleId = value.payoutScheduleId;
        this.wtime = value.wtime;
        this.current = value.current;
        this.revision = value.revision;
    }

    public Shop(
        Long          id,
        Long          eventId,
        LocalDateTime eventCreatedAt,
        String        partyId,
        String        shopId,
        LocalDateTime createdAt,
        Blocking      blocking,
        String        blockingUnblockedReason,
        LocalDateTime blockingUnblockedSince,
        String        blockingBlockedReason,
        LocalDateTime blockingBlockedSince,
        Suspension    suspension,
        LocalDateTime suspensionActiveSince,
        LocalDateTime suspensionSuspendedSince,
        String        detailsName,
        String        detailsDescription,
        String        locationUrl,
        Integer       categoryId,
        String        accountCurrencyCode,
        Long          accountSettlement,
        Long          accountGuarantee,
        Long          accountPayout,
        String        contractId,
        String        payoutToolId,
        Integer       payoutScheduleId,
        LocalDateTime wtime,
        Boolean       current,
        Long          revision
    ) {
        this.id = id;
        this.eventId = eventId;
        this.eventCreatedAt = eventCreatedAt;
        this.partyId = partyId;
        this.shopId = shopId;
        this.createdAt = createdAt;
        this.blocking = blocking;
        this.blockingUnblockedReason = blockingUnblockedReason;
        this.blockingUnblockedSince = blockingUnblockedSince;
        this.blockingBlockedReason = blockingBlockedReason;
        this.blockingBlockedSince = blockingBlockedSince;
        this.suspension = suspension;
        this.suspensionActiveSince = suspensionActiveSince;
        this.suspensionSuspendedSince = suspensionSuspendedSince;
        this.detailsName = detailsName;
        this.detailsDescription = detailsDescription;
        this.locationUrl = locationUrl;
        this.categoryId = categoryId;
        this.accountCurrencyCode = accountCurrencyCode;
        this.accountSettlement = accountSettlement;
        this.accountGuarantee = accountGuarantee;
        this.accountPayout = accountPayout;
        this.contractId = contractId;
        this.payoutToolId = payoutToolId;
        this.payoutScheduleId = payoutScheduleId;
        this.wtime = wtime;
        this.current = current;
        this.revision = revision;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getEventId() {
        return this.eventId;
    }

    public void setEventId(Long eventId) {
        this.eventId = eventId;
    }

    public LocalDateTime getEventCreatedAt() {
        return this.eventCreatedAt;
    }

    public void setEventCreatedAt(LocalDateTime eventCreatedAt) {
        this.eventCreatedAt = eventCreatedAt;
    }

    public String getPartyId() {
        return this.partyId;
    }

    public void setPartyId(String partyId) {
        this.partyId = partyId;
    }

    public String getShopId() {
        return this.shopId;
    }

    public void setShopId(String shopId) {
        this.shopId = shopId;
    }

    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public Blocking getBlocking() {
        return this.blocking;
    }

    public void setBlocking(Blocking blocking) {
        this.blocking = blocking;
    }

    public String getBlockingUnblockedReason() {
        return this.blockingUnblockedReason;
    }

    public void setBlockingUnblockedReason(String blockingUnblockedReason) {
        this.blockingUnblockedReason = blockingUnblockedReason;
    }

    public LocalDateTime getBlockingUnblockedSince() {
        return this.blockingUnblockedSince;
    }

    public void setBlockingUnblockedSince(LocalDateTime blockingUnblockedSince) {
        this.blockingUnblockedSince = blockingUnblockedSince;
    }

    public String getBlockingBlockedReason() {
        return this.blockingBlockedReason;
    }

    public void setBlockingBlockedReason(String blockingBlockedReason) {
        this.blockingBlockedReason = blockingBlockedReason;
    }

    public LocalDateTime getBlockingBlockedSince() {
        return this.blockingBlockedSince;
    }

    public void setBlockingBlockedSince(LocalDateTime blockingBlockedSince) {
        this.blockingBlockedSince = blockingBlockedSince;
    }

    public Suspension getSuspension() {
        return this.suspension;
    }

    public void setSuspension(Suspension suspension) {
        this.suspension = suspension;
    }

    public LocalDateTime getSuspensionActiveSince() {
        return this.suspensionActiveSince;
    }

    public void setSuspensionActiveSince(LocalDateTime suspensionActiveSince) {
        this.suspensionActiveSince = suspensionActiveSince;
    }

    public LocalDateTime getSuspensionSuspendedSince() {
        return this.suspensionSuspendedSince;
    }

    public void setSuspensionSuspendedSince(LocalDateTime suspensionSuspendedSince) {
        this.suspensionSuspendedSince = suspensionSuspendedSince;
    }

    public String getDetailsName() {
        return this.detailsName;
    }

    public void setDetailsName(String detailsName) {
        this.detailsName = detailsName;
    }

    public String getDetailsDescription() {
        return this.detailsDescription;
    }

    public void setDetailsDescription(String detailsDescription) {
        this.detailsDescription = detailsDescription;
    }

    public String getLocationUrl() {
        return this.locationUrl;
    }

    public void setLocationUrl(String locationUrl) {
        this.locationUrl = locationUrl;
    }

    public Integer getCategoryId() {
        return this.categoryId;
    }

    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    public String getAccountCurrencyCode() {
        return this.accountCurrencyCode;
    }

    public void setAccountCurrencyCode(String accountCurrencyCode) {
        this.accountCurrencyCode = accountCurrencyCode;
    }

    public Long getAccountSettlement() {
        return this.accountSettlement;
    }

    public void setAccountSettlement(Long accountSettlement) {
        this.accountSettlement = accountSettlement;
    }

    public Long getAccountGuarantee() {
        return this.accountGuarantee;
    }

    public void setAccountGuarantee(Long accountGuarantee) {
        this.accountGuarantee = accountGuarantee;
    }

    public Long getAccountPayout() {
        return this.accountPayout;
    }

    public void setAccountPayout(Long accountPayout) {
        this.accountPayout = accountPayout;
    }

    public String getContractId() {
        return this.contractId;
    }

    public void setContractId(String contractId) {
        this.contractId = contractId;
    }

    public String getPayoutToolId() {
        return this.payoutToolId;
    }

    public void setPayoutToolId(String payoutToolId) {
        this.payoutToolId = payoutToolId;
    }

    public Integer getPayoutScheduleId() {
        return this.payoutScheduleId;
    }

    public void setPayoutScheduleId(Integer payoutScheduleId) {
        this.payoutScheduleId = payoutScheduleId;
    }

    public LocalDateTime getWtime() {
        return this.wtime;
    }

    public void setWtime(LocalDateTime wtime) {
        this.wtime = wtime;
    }

    public Boolean getCurrent() {
        return this.current;
    }

    public void setCurrent(Boolean current) {
        this.current = current;
    }

    public Long getRevision() {
        return this.revision;
    }

    public void setRevision(Long revision) {
        this.revision = revision;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Shop other = (Shop) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (eventId == null) {
            if (other.eventId != null)
                return false;
        }
        else if (!eventId.equals(other.eventId))
            return false;
        if (eventCreatedAt == null) {
            if (other.eventCreatedAt != null)
                return false;
        }
        else if (!eventCreatedAt.equals(other.eventCreatedAt))
            return false;
        if (partyId == null) {
            if (other.partyId != null)
                return false;
        }
        else if (!partyId.equals(other.partyId))
            return false;
        if (shopId == null) {
            if (other.shopId != null)
                return false;
        }
        else if (!shopId.equals(other.shopId))
            return false;
        if (createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!createdAt.equals(other.createdAt))
            return false;
        if (blocking == null) {
            if (other.blocking != null)
                return false;
        }
        else if (!blocking.equals(other.blocking))
            return false;
        if (blockingUnblockedReason == null) {
            if (other.blockingUnblockedReason != null)
                return false;
        }
        else if (!blockingUnblockedReason.equals(other.blockingUnblockedReason))
            return false;
        if (blockingUnblockedSince == null) {
            if (other.blockingUnblockedSince != null)
                return false;
        }
        else if (!blockingUnblockedSince.equals(other.blockingUnblockedSince))
            return false;
        if (blockingBlockedReason == null) {
            if (other.blockingBlockedReason != null)
                return false;
        }
        else if (!blockingBlockedReason.equals(other.blockingBlockedReason))
            return false;
        if (blockingBlockedSince == null) {
            if (other.blockingBlockedSince != null)
                return false;
        }
        else if (!blockingBlockedSince.equals(other.blockingBlockedSince))
            return false;
        if (suspension == null) {
            if (other.suspension != null)
                return false;
        }
        else if (!suspension.equals(other.suspension))
            return false;
        if (suspensionActiveSince == null) {
            if (other.suspensionActiveSince != null)
                return false;
        }
        else if (!suspensionActiveSince.equals(other.suspensionActiveSince))
            return false;
        if (suspensionSuspendedSince == null) {
            if (other.suspensionSuspendedSince != null)
                return false;
        }
        else if (!suspensionSuspendedSince.equals(other.suspensionSuspendedSince))
            return false;
        if (detailsName == null) {
            if (other.detailsName != null)
                return false;
        }
        else if (!detailsName.equals(other.detailsName))
            return false;
        if (detailsDescription == null) {
            if (other.detailsDescription != null)
                return false;
        }
        else if (!detailsDescription.equals(other.detailsDescription))
            return false;
        if (locationUrl == null) {
            if (other.locationUrl != null)
                return false;
        }
        else if (!locationUrl.equals(other.locationUrl))
            return false;
        if (categoryId == null) {
            if (other.categoryId != null)
                return false;
        }
        else if (!categoryId.equals(other.categoryId))
            return false;
        if (accountCurrencyCode == null) {
            if (other.accountCurrencyCode != null)
                return false;
        }
        else if (!accountCurrencyCode.equals(other.accountCurrencyCode))
            return false;
        if (accountSettlement == null) {
            if (other.accountSettlement != null)
                return false;
        }
        else if (!accountSettlement.equals(other.accountSettlement))
            return false;
        if (accountGuarantee == null) {
            if (other.accountGuarantee != null)
                return false;
        }
        else if (!accountGuarantee.equals(other.accountGuarantee))
            return false;
        if (accountPayout == null) {
            if (other.accountPayout != null)
                return false;
        }
        else if (!accountPayout.equals(other.accountPayout))
            return false;
        if (contractId == null) {
            if (other.contractId != null)
                return false;
        }
        else if (!contractId.equals(other.contractId))
            return false;
        if (payoutToolId == null) {
            if (other.payoutToolId != null)
                return false;
        }
        else if (!payoutToolId.equals(other.payoutToolId))
            return false;
        if (payoutScheduleId == null) {
            if (other.payoutScheduleId != null)
                return false;
        }
        else if (!payoutScheduleId.equals(other.payoutScheduleId))
            return false;
        if (wtime == null) {
            if (other.wtime != null)
                return false;
        }
        else if (!wtime.equals(other.wtime))
            return false;
        if (current == null) {
            if (other.current != null)
                return false;
        }
        else if (!current.equals(other.current))
            return false;
        if (revision == null) {
            if (other.revision != null)
                return false;
        }
        else if (!revision.equals(other.revision))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.eventId == null) ? 0 : this.eventId.hashCode());
        result = prime * result + ((this.eventCreatedAt == null) ? 0 : this.eventCreatedAt.hashCode());
        result = prime * result + ((this.partyId == null) ? 0 : this.partyId.hashCode());
        result = prime * result + ((this.shopId == null) ? 0 : this.shopId.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        result = prime * result + ((this.blocking == null) ? 0 : this.blocking.hashCode());
        result = prime * result + ((this.blockingUnblockedReason == null) ? 0 : this.blockingUnblockedReason.hashCode());
        result = prime * result + ((this.blockingUnblockedSince == null) ? 0 : this.blockingUnblockedSince.hashCode());
        result = prime * result + ((this.blockingBlockedReason == null) ? 0 : this.blockingBlockedReason.hashCode());
        result = prime * result + ((this.blockingBlockedSince == null) ? 0 : this.blockingBlockedSince.hashCode());
        result = prime * result + ((this.suspension == null) ? 0 : this.suspension.hashCode());
        result = prime * result + ((this.suspensionActiveSince == null) ? 0 : this.suspensionActiveSince.hashCode());
        result = prime * result + ((this.suspensionSuspendedSince == null) ? 0 : this.suspensionSuspendedSince.hashCode());
        result = prime * result + ((this.detailsName == null) ? 0 : this.detailsName.hashCode());
        result = prime * result + ((this.detailsDescription == null) ? 0 : this.detailsDescription.hashCode());
        result = prime * result + ((this.locationUrl == null) ? 0 : this.locationUrl.hashCode());
        result = prime * result + ((this.categoryId == null) ? 0 : this.categoryId.hashCode());
        result = prime * result + ((this.accountCurrencyCode == null) ? 0 : this.accountCurrencyCode.hashCode());
        result = prime * result + ((this.accountSettlement == null) ? 0 : this.accountSettlement.hashCode());
        result = prime * result + ((this.accountGuarantee == null) ? 0 : this.accountGuarantee.hashCode());
        result = prime * result + ((this.accountPayout == null) ? 0 : this.accountPayout.hashCode());
        result = prime * result + ((this.contractId == null) ? 0 : this.contractId.hashCode());
        result = prime * result + ((this.payoutToolId == null) ? 0 : this.payoutToolId.hashCode());
        result = prime * result + ((this.payoutScheduleId == null) ? 0 : this.payoutScheduleId.hashCode());
        result = prime * result + ((this.wtime == null) ? 0 : this.wtime.hashCode());
        result = prime * result + ((this.current == null) ? 0 : this.current.hashCode());
        result = prime * result + ((this.revision == null) ? 0 : this.revision.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Shop (");

        sb.append(id);
        sb.append(", ").append(eventId);
        sb.append(", ").append(eventCreatedAt);
        sb.append(", ").append(partyId);
        sb.append(", ").append(shopId);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(blocking);
        sb.append(", ").append(blockingUnblockedReason);
        sb.append(", ").append(blockingUnblockedSince);
        sb.append(", ").append(blockingBlockedReason);
        sb.append(", ").append(blockingBlockedSince);
        sb.append(", ").append(suspension);
        sb.append(", ").append(suspensionActiveSince);
        sb.append(", ").append(suspensionSuspendedSince);
        sb.append(", ").append(detailsName);
        sb.append(", ").append(detailsDescription);
        sb.append(", ").append(locationUrl);
        sb.append(", ").append(categoryId);
        sb.append(", ").append(accountCurrencyCode);
        sb.append(", ").append(accountSettlement);
        sb.append(", ").append(accountGuarantee);
        sb.append(", ").append(accountPayout);
        sb.append(", ").append(contractId);
        sb.append(", ").append(payoutToolId);
        sb.append(", ").append(payoutScheduleId);
        sb.append(", ").append(wtime);
        sb.append(", ").append(current);
        sb.append(", ").append(revision);

        sb.append(")");
        return sb.toString();
    }
}
