ALTER TABLE nw.deposit ADD COLUMN external_id CHARACTER VARYING;
ALTER TABLE nw.destination ADD COLUMN external_id CHARACTER VARYING;
ALTER TABLE nw.identity ADD COLUMN external_id CHARACTER VARYING;
ALTER TABLE nw.source ADD COLUMN external_id CHARACTER VARYING;
ALTER TABLE nw.wallet ADD COLUMN external_id CHARACTER VARYING;
ALTER TABLE nw.withdrawal ADD COLUMN external_id CHARACTER VARYING;

ALTER TABLE nw.identity ADD COLUMN blocked BOOLEAN;
ALTER TABLE nw.identity ADD COLUMN context_json CHARACTER VARYING;
ALTER TABLE nw.challenge ADD COLUMN proofs_json CHARACTER VARYING;

ALTER TABLE nw.destination ADD COLUMN created_at TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE nw.destination ADD COLUMN context_json CHARACTER VARYING;
ALTER TABLE nw.withdrawal ADD COLUMN context_json CHARACTER VARYING;

ALTER TABLE nw.withdrawal_session ADD COLUMN failure_json CHARACTER VARYING;
