/*
 * This file is generated by jOOQ.
*/
package com.rbkmoney.newway.domain;


import com.rbkmoney.newway.domain.enums.CashFlowAccount;
import com.rbkmoney.newway.domain.enums.PaymentChangeType;
import com.rbkmoney.newway.domain.routines.CashflowSumFinalfunc;
import com.rbkmoney.newway.domain.routines.GetAdjustmentAmount;
import com.rbkmoney.newway.domain.routines.GetAdjustmentAmountSfunc;
import com.rbkmoney.newway.domain.routines.GetAdjustmentExternalFee;
import com.rbkmoney.newway.domain.routines.GetAdjustmentExternalFeeSfunc;
import com.rbkmoney.newway.domain.routines.GetAdjustmentFee;
import com.rbkmoney.newway.domain.routines.GetAdjustmentFeeSfunc;
import com.rbkmoney.newway.domain.routines.GetAdjustmentProviderFee;
import com.rbkmoney.newway.domain.routines.GetAdjustmentProviderFeeSfunc;
import com.rbkmoney.newway.domain.routines.GetCashflowSum;
import com.rbkmoney.newway.domain.routines.GetPaymentAmount;
import com.rbkmoney.newway.domain.routines.GetPaymentAmountSfunc;
import com.rbkmoney.newway.domain.routines.GetPaymentExternalFee;
import com.rbkmoney.newway.domain.routines.GetPaymentExternalFeeSfunc;
import com.rbkmoney.newway.domain.routines.GetPaymentFee;
import com.rbkmoney.newway.domain.routines.GetPaymentFeeSfunc;
import com.rbkmoney.newway.domain.routines.GetPaymentGuaranteeDeposit;
import com.rbkmoney.newway.domain.routines.GetPaymentGuaranteeDepositSfunc;
import com.rbkmoney.newway.domain.routines.GetPaymentProviderFee;
import com.rbkmoney.newway.domain.routines.GetPaymentProviderFeeSfunc;
import com.rbkmoney.newway.domain.routines.GetPayoutAmount;
import com.rbkmoney.newway.domain.routines.GetPayoutAmountSfunc;
import com.rbkmoney.newway.domain.routines.GetPayoutFee;
import com.rbkmoney.newway.domain.routines.GetPayoutFeeSfunc;
import com.rbkmoney.newway.domain.routines.GetPayoutFixedFee;
import com.rbkmoney.newway.domain.routines.GetPayoutFixedFeeSfunc;
import com.rbkmoney.newway.domain.routines.GetRefundAmount;
import com.rbkmoney.newway.domain.routines.GetRefundAmountSfunc;
import com.rbkmoney.newway.domain.routines.GetRefundExternalFee;
import com.rbkmoney.newway.domain.routines.GetRefundExternalFeeSfunc;
import com.rbkmoney.newway.domain.routines.GetRefundFee;
import com.rbkmoney.newway.domain.routines.GetRefundFeeSfunc;
import com.rbkmoney.newway.domain.routines.GetRefundProviderFee;
import com.rbkmoney.newway.domain.routines.GetRefundProviderFeeSfunc;
import com.rbkmoney.newway.domain.tables.records.CashFlowRecord;

import javax.annotation.Generated;

import org.jooq.AggregateFunction;
import org.jooq.Configuration;
import org.jooq.Field;


/**
 * Convenience access to all stored procedures and functions in nw
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Routines {

    /**
     * Call <code>nw.cashflow_sum_finalfunc</code>
     */
    public static Long cashflowSumFinalfunc(Configuration configuration, Long[] amounts) {
        CashflowSumFinalfunc f = new CashflowSumFinalfunc();
        f.setAmounts(amounts);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>nw.cashflow_sum_finalfunc</code> as a field.
     */
    public static Field<Long> cashflowSumFinalfunc(Long[] amounts) {
        CashflowSumFinalfunc f = new CashflowSumFinalfunc();
        f.setAmounts(amounts);

        return f.asField();
    }

    /**
     * Get <code>nw.cashflow_sum_finalfunc</code> as a field.
     */
    public static Field<Long> cashflowSumFinalfunc(Field<Long[]> amounts) {
        CashflowSumFinalfunc f = new CashflowSumFinalfunc();
        f.setAmounts(amounts);

        return f.asField();
    }

    /**
     * Get <code>nw.get_adjustment_amount</code> as a field.
     */
    public static AggregateFunction<Long> getAdjustmentAmount(CashFlowRecord __1) {
        GetAdjustmentAmount f = new GetAdjustmentAmount();
        f.set__1(__1);

        return f.asAggregateFunction();
    }

    /**
     * Get <code>nw.get_adjustment_amount</code> as a field.
     */
    public static AggregateFunction<Long> getAdjustmentAmount(Field<CashFlowRecord> __1) {
        GetAdjustmentAmount f = new GetAdjustmentAmount();
        f.set__1(__1);

        return f.asAggregateFunction();
    }

    /**
     * Call <code>nw.get_adjustment_amount_sfunc</code>
     */
    public static Long[] getAdjustmentAmountSfunc(Configuration configuration, Long[] amounts, CashFlowRecord cashFlow) {
        GetAdjustmentAmountSfunc f = new GetAdjustmentAmountSfunc();
        f.setAmounts(amounts);
        f.setCashFlow(cashFlow);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>nw.get_adjustment_amount_sfunc</code> as a field.
     */
    public static Field<Long[]> getAdjustmentAmountSfunc(Long[] amounts, CashFlowRecord cashFlow) {
        GetAdjustmentAmountSfunc f = new GetAdjustmentAmountSfunc();
        f.setAmounts(amounts);
        f.setCashFlow(cashFlow);

        return f.asField();
    }

    /**
     * Get <code>nw.get_adjustment_amount_sfunc</code> as a field.
     */
    public static Field<Long[]> getAdjustmentAmountSfunc(Field<Long[]> amounts, Field<CashFlowRecord> cashFlow) {
        GetAdjustmentAmountSfunc f = new GetAdjustmentAmountSfunc();
        f.setAmounts(amounts);
        f.setCashFlow(cashFlow);

        return f.asField();
    }

    /**
     * Get <code>nw.get_adjustment_external_fee</code> as a field.
     */
    public static AggregateFunction<Long> getAdjustmentExternalFee(CashFlowRecord __1) {
        GetAdjustmentExternalFee f = new GetAdjustmentExternalFee();
        f.set__1(__1);

        return f.asAggregateFunction();
    }

    /**
     * Get <code>nw.get_adjustment_external_fee</code> as a field.
     */
    public static AggregateFunction<Long> getAdjustmentExternalFee(Field<CashFlowRecord> __1) {
        GetAdjustmentExternalFee f = new GetAdjustmentExternalFee();
        f.set__1(__1);

        return f.asAggregateFunction();
    }

    /**
     * Call <code>nw.get_adjustment_external_fee_sfunc</code>
     */
    public static Long[] getAdjustmentExternalFeeSfunc(Configuration configuration, Long[] amounts, CashFlowRecord cashFlow) {
        GetAdjustmentExternalFeeSfunc f = new GetAdjustmentExternalFeeSfunc();
        f.setAmounts(amounts);
        f.setCashFlow(cashFlow);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>nw.get_adjustment_external_fee_sfunc</code> as a field.
     */
    public static Field<Long[]> getAdjustmentExternalFeeSfunc(Long[] amounts, CashFlowRecord cashFlow) {
        GetAdjustmentExternalFeeSfunc f = new GetAdjustmentExternalFeeSfunc();
        f.setAmounts(amounts);
        f.setCashFlow(cashFlow);

        return f.asField();
    }

    /**
     * Get <code>nw.get_adjustment_external_fee_sfunc</code> as a field.
     */
    public static Field<Long[]> getAdjustmentExternalFeeSfunc(Field<Long[]> amounts, Field<CashFlowRecord> cashFlow) {
        GetAdjustmentExternalFeeSfunc f = new GetAdjustmentExternalFeeSfunc();
        f.setAmounts(amounts);
        f.setCashFlow(cashFlow);

        return f.asField();
    }

    /**
     * Get <code>nw.get_adjustment_fee</code> as a field.
     */
    public static AggregateFunction<Long> getAdjustmentFee(CashFlowRecord __1) {
        GetAdjustmentFee f = new GetAdjustmentFee();
        f.set__1(__1);

        return f.asAggregateFunction();
    }

    /**
     * Get <code>nw.get_adjustment_fee</code> as a field.
     */
    public static AggregateFunction<Long> getAdjustmentFee(Field<CashFlowRecord> __1) {
        GetAdjustmentFee f = new GetAdjustmentFee();
        f.set__1(__1);

        return f.asAggregateFunction();
    }

    /**
     * Call <code>nw.get_adjustment_fee_sfunc</code>
     */
    public static Long[] getAdjustmentFeeSfunc(Configuration configuration, Long[] amounts, CashFlowRecord cashFlow) {
        GetAdjustmentFeeSfunc f = new GetAdjustmentFeeSfunc();
        f.setAmounts(amounts);
        f.setCashFlow(cashFlow);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>nw.get_adjustment_fee_sfunc</code> as a field.
     */
    public static Field<Long[]> getAdjustmentFeeSfunc(Long[] amounts, CashFlowRecord cashFlow) {
        GetAdjustmentFeeSfunc f = new GetAdjustmentFeeSfunc();
        f.setAmounts(amounts);
        f.setCashFlow(cashFlow);

        return f.asField();
    }

    /**
     * Get <code>nw.get_adjustment_fee_sfunc</code> as a field.
     */
    public static Field<Long[]> getAdjustmentFeeSfunc(Field<Long[]> amounts, Field<CashFlowRecord> cashFlow) {
        GetAdjustmentFeeSfunc f = new GetAdjustmentFeeSfunc();
        f.setAmounts(amounts);
        f.setCashFlow(cashFlow);

        return f.asField();
    }

    /**
     * Get <code>nw.get_adjustment_provider_fee</code> as a field.
     */
    public static AggregateFunction<Long> getAdjustmentProviderFee(CashFlowRecord __1) {
        GetAdjustmentProviderFee f = new GetAdjustmentProviderFee();
        f.set__1(__1);

        return f.asAggregateFunction();
    }

    /**
     * Get <code>nw.get_adjustment_provider_fee</code> as a field.
     */
    public static AggregateFunction<Long> getAdjustmentProviderFee(Field<CashFlowRecord> __1) {
        GetAdjustmentProviderFee f = new GetAdjustmentProviderFee();
        f.set__1(__1);

        return f.asAggregateFunction();
    }

    /**
     * Call <code>nw.get_adjustment_provider_fee_sfunc</code>
     */
    public static Long[] getAdjustmentProviderFeeSfunc(Configuration configuration, Long[] amounts, CashFlowRecord cashFlow) {
        GetAdjustmentProviderFeeSfunc f = new GetAdjustmentProviderFeeSfunc();
        f.setAmounts(amounts);
        f.setCashFlow(cashFlow);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>nw.get_adjustment_provider_fee_sfunc</code> as a field.
     */
    public static Field<Long[]> getAdjustmentProviderFeeSfunc(Long[] amounts, CashFlowRecord cashFlow) {
        GetAdjustmentProviderFeeSfunc f = new GetAdjustmentProviderFeeSfunc();
        f.setAmounts(amounts);
        f.setCashFlow(cashFlow);

        return f.asField();
    }

    /**
     * Get <code>nw.get_adjustment_provider_fee_sfunc</code> as a field.
     */
    public static Field<Long[]> getAdjustmentProviderFeeSfunc(Field<Long[]> amounts, Field<CashFlowRecord> cashFlow) {
        GetAdjustmentProviderFeeSfunc f = new GetAdjustmentProviderFeeSfunc();
        f.setAmounts(amounts);
        f.setCashFlow(cashFlow);

        return f.asField();
    }

    /**
     * Call <code>nw.get_cashflow_sum</code>
     */
    public static Long getCashflowSum(Configuration configuration, CashFlowRecord _CashFlow, PaymentChangeType objType, CashFlowAccount sourceAccountType, String[] sourceAccountTypeValues, CashFlowAccount destinationAccountType, String[] destinationAccountTypeValues) {
        GetCashflowSum f = new GetCashflowSum();
        f.set_CashFlow(_CashFlow);
        f.setObjType(objType);
        f.setSourceAccountType(sourceAccountType);
        f.setSourceAccountTypeValues(sourceAccountTypeValues);
        f.setDestinationAccountType(destinationAccountType);
        f.setDestinationAccountTypeValues(destinationAccountTypeValues);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>nw.get_cashflow_sum</code> as a field.
     */
    public static Field<Long> getCashflowSum(CashFlowRecord _CashFlow, PaymentChangeType objType, CashFlowAccount sourceAccountType, String[] sourceAccountTypeValues, CashFlowAccount destinationAccountType, String[] destinationAccountTypeValues) {
        GetCashflowSum f = new GetCashflowSum();
        f.set_CashFlow(_CashFlow);
        f.setObjType(objType);
        f.setSourceAccountType(sourceAccountType);
        f.setSourceAccountTypeValues(sourceAccountTypeValues);
        f.setDestinationAccountType(destinationAccountType);
        f.setDestinationAccountTypeValues(destinationAccountTypeValues);

        return f.asField();
    }

    /**
     * Get <code>nw.get_cashflow_sum</code> as a field.
     */
    public static Field<Long> getCashflowSum(Field<CashFlowRecord> _CashFlow, Field<PaymentChangeType> objType, Field<CashFlowAccount> sourceAccountType, Field<String[]> sourceAccountTypeValues, Field<CashFlowAccount> destinationAccountType, Field<String[]> destinationAccountTypeValues) {
        GetCashflowSum f = new GetCashflowSum();
        f.set_CashFlow(_CashFlow);
        f.setObjType(objType);
        f.setSourceAccountType(sourceAccountType);
        f.setSourceAccountTypeValues(sourceAccountTypeValues);
        f.setDestinationAccountType(destinationAccountType);
        f.setDestinationAccountTypeValues(destinationAccountTypeValues);

        return f.asField();
    }

    /**
     * Get <code>nw.get_payment_amount</code> as a field.
     */
    public static AggregateFunction<Long> getPaymentAmount(CashFlowRecord __1) {
        GetPaymentAmount f = new GetPaymentAmount();
        f.set__1(__1);

        return f.asAggregateFunction();
    }

    /**
     * Get <code>nw.get_payment_amount</code> as a field.
     */
    public static AggregateFunction<Long> getPaymentAmount(Field<CashFlowRecord> __1) {
        GetPaymentAmount f = new GetPaymentAmount();
        f.set__1(__1);

        return f.asAggregateFunction();
    }

    /**
     * Call <code>nw.get_payment_amount_sfunc</code>
     */
    public static Long[] getPaymentAmountSfunc(Configuration configuration, Long[] amounts, CashFlowRecord cashFlow) {
        GetPaymentAmountSfunc f = new GetPaymentAmountSfunc();
        f.setAmounts(amounts);
        f.setCashFlow(cashFlow);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>nw.get_payment_amount_sfunc</code> as a field.
     */
    public static Field<Long[]> getPaymentAmountSfunc(Long[] amounts, CashFlowRecord cashFlow) {
        GetPaymentAmountSfunc f = new GetPaymentAmountSfunc();
        f.setAmounts(amounts);
        f.setCashFlow(cashFlow);

        return f.asField();
    }

    /**
     * Get <code>nw.get_payment_amount_sfunc</code> as a field.
     */
    public static Field<Long[]> getPaymentAmountSfunc(Field<Long[]> amounts, Field<CashFlowRecord> cashFlow) {
        GetPaymentAmountSfunc f = new GetPaymentAmountSfunc();
        f.setAmounts(amounts);
        f.setCashFlow(cashFlow);

        return f.asField();
    }

    /**
     * Get <code>nw.get_payment_external_fee</code> as a field.
     */
    public static AggregateFunction<Long> getPaymentExternalFee(CashFlowRecord __1) {
        GetPaymentExternalFee f = new GetPaymentExternalFee();
        f.set__1(__1);

        return f.asAggregateFunction();
    }

    /**
     * Get <code>nw.get_payment_external_fee</code> as a field.
     */
    public static AggregateFunction<Long> getPaymentExternalFee(Field<CashFlowRecord> __1) {
        GetPaymentExternalFee f = new GetPaymentExternalFee();
        f.set__1(__1);

        return f.asAggregateFunction();
    }

    /**
     * Call <code>nw.get_payment_external_fee_sfunc</code>
     */
    public static Long[] getPaymentExternalFeeSfunc(Configuration configuration, Long[] amounts, CashFlowRecord cashFlow) {
        GetPaymentExternalFeeSfunc f = new GetPaymentExternalFeeSfunc();
        f.setAmounts(amounts);
        f.setCashFlow(cashFlow);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>nw.get_payment_external_fee_sfunc</code> as a field.
     */
    public static Field<Long[]> getPaymentExternalFeeSfunc(Long[] amounts, CashFlowRecord cashFlow) {
        GetPaymentExternalFeeSfunc f = new GetPaymentExternalFeeSfunc();
        f.setAmounts(amounts);
        f.setCashFlow(cashFlow);

        return f.asField();
    }

    /**
     * Get <code>nw.get_payment_external_fee_sfunc</code> as a field.
     */
    public static Field<Long[]> getPaymentExternalFeeSfunc(Field<Long[]> amounts, Field<CashFlowRecord> cashFlow) {
        GetPaymentExternalFeeSfunc f = new GetPaymentExternalFeeSfunc();
        f.setAmounts(amounts);
        f.setCashFlow(cashFlow);

        return f.asField();
    }

    /**
     * Get <code>nw.get_payment_fee</code> as a field.
     */
    public static AggregateFunction<Long> getPaymentFee(CashFlowRecord __1) {
        GetPaymentFee f = new GetPaymentFee();
        f.set__1(__1);

        return f.asAggregateFunction();
    }

    /**
     * Get <code>nw.get_payment_fee</code> as a field.
     */
    public static AggregateFunction<Long> getPaymentFee(Field<CashFlowRecord> __1) {
        GetPaymentFee f = new GetPaymentFee();
        f.set__1(__1);

        return f.asAggregateFunction();
    }

    /**
     * Call <code>nw.get_payment_fee_sfunc</code>
     */
    public static Long[] getPaymentFeeSfunc(Configuration configuration, Long[] amounts, CashFlowRecord cashFlow) {
        GetPaymentFeeSfunc f = new GetPaymentFeeSfunc();
        f.setAmounts(amounts);
        f.setCashFlow(cashFlow);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>nw.get_payment_fee_sfunc</code> as a field.
     */
    public static Field<Long[]> getPaymentFeeSfunc(Long[] amounts, CashFlowRecord cashFlow) {
        GetPaymentFeeSfunc f = new GetPaymentFeeSfunc();
        f.setAmounts(amounts);
        f.setCashFlow(cashFlow);

        return f.asField();
    }

    /**
     * Get <code>nw.get_payment_fee_sfunc</code> as a field.
     */
    public static Field<Long[]> getPaymentFeeSfunc(Field<Long[]> amounts, Field<CashFlowRecord> cashFlow) {
        GetPaymentFeeSfunc f = new GetPaymentFeeSfunc();
        f.setAmounts(amounts);
        f.setCashFlow(cashFlow);

        return f.asField();
    }

    /**
     * Get <code>nw.get_payment_guarantee_deposit</code> as a field.
     */
    public static AggregateFunction<Long> getPaymentGuaranteeDeposit(CashFlowRecord __1) {
        GetPaymentGuaranteeDeposit f = new GetPaymentGuaranteeDeposit();
        f.set__1(__1);

        return f.asAggregateFunction();
    }

    /**
     * Get <code>nw.get_payment_guarantee_deposit</code> as a field.
     */
    public static AggregateFunction<Long> getPaymentGuaranteeDeposit(Field<CashFlowRecord> __1) {
        GetPaymentGuaranteeDeposit f = new GetPaymentGuaranteeDeposit();
        f.set__1(__1);

        return f.asAggregateFunction();
    }

    /**
     * Call <code>nw.get_payment_guarantee_deposit_sfunc</code>
     */
    public static Long[] getPaymentGuaranteeDepositSfunc(Configuration configuration, Long[] amounts, CashFlowRecord cashFlow) {
        GetPaymentGuaranteeDepositSfunc f = new GetPaymentGuaranteeDepositSfunc();
        f.setAmounts(amounts);
        f.setCashFlow(cashFlow);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>nw.get_payment_guarantee_deposit_sfunc</code> as a field.
     */
    public static Field<Long[]> getPaymentGuaranteeDepositSfunc(Long[] amounts, CashFlowRecord cashFlow) {
        GetPaymentGuaranteeDepositSfunc f = new GetPaymentGuaranteeDepositSfunc();
        f.setAmounts(amounts);
        f.setCashFlow(cashFlow);

        return f.asField();
    }

    /**
     * Get <code>nw.get_payment_guarantee_deposit_sfunc</code> as a field.
     */
    public static Field<Long[]> getPaymentGuaranteeDepositSfunc(Field<Long[]> amounts, Field<CashFlowRecord> cashFlow) {
        GetPaymentGuaranteeDepositSfunc f = new GetPaymentGuaranteeDepositSfunc();
        f.setAmounts(amounts);
        f.setCashFlow(cashFlow);

        return f.asField();
    }

    /**
     * Get <code>nw.get_payment_provider_fee</code> as a field.
     */
    public static AggregateFunction<Long> getPaymentProviderFee(CashFlowRecord __1) {
        GetPaymentProviderFee f = new GetPaymentProviderFee();
        f.set__1(__1);

        return f.asAggregateFunction();
    }

    /**
     * Get <code>nw.get_payment_provider_fee</code> as a field.
     */
    public static AggregateFunction<Long> getPaymentProviderFee(Field<CashFlowRecord> __1) {
        GetPaymentProviderFee f = new GetPaymentProviderFee();
        f.set__1(__1);

        return f.asAggregateFunction();
    }

    /**
     * Call <code>nw.get_payment_provider_fee_sfunc</code>
     */
    public static Long[] getPaymentProviderFeeSfunc(Configuration configuration, Long[] amounts, CashFlowRecord cashFlow) {
        GetPaymentProviderFeeSfunc f = new GetPaymentProviderFeeSfunc();
        f.setAmounts(amounts);
        f.setCashFlow(cashFlow);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>nw.get_payment_provider_fee_sfunc</code> as a field.
     */
    public static Field<Long[]> getPaymentProviderFeeSfunc(Long[] amounts, CashFlowRecord cashFlow) {
        GetPaymentProviderFeeSfunc f = new GetPaymentProviderFeeSfunc();
        f.setAmounts(amounts);
        f.setCashFlow(cashFlow);

        return f.asField();
    }

    /**
     * Get <code>nw.get_payment_provider_fee_sfunc</code> as a field.
     */
    public static Field<Long[]> getPaymentProviderFeeSfunc(Field<Long[]> amounts, Field<CashFlowRecord> cashFlow) {
        GetPaymentProviderFeeSfunc f = new GetPaymentProviderFeeSfunc();
        f.setAmounts(amounts);
        f.setCashFlow(cashFlow);

        return f.asField();
    }

    /**
     * Get <code>nw.get_payout_amount</code> as a field.
     */
    public static AggregateFunction<Long> getPayoutAmount(CashFlowRecord __1) {
        GetPayoutAmount f = new GetPayoutAmount();
        f.set__1(__1);

        return f.asAggregateFunction();
    }

    /**
     * Get <code>nw.get_payout_amount</code> as a field.
     */
    public static AggregateFunction<Long> getPayoutAmount(Field<CashFlowRecord> __1) {
        GetPayoutAmount f = new GetPayoutAmount();
        f.set__1(__1);

        return f.asAggregateFunction();
    }

    /**
     * Call <code>nw.get_payout_amount_sfunc</code>
     */
    public static Long[] getPayoutAmountSfunc(Configuration configuration, Long[] amounts, CashFlowRecord cashFlow) {
        GetPayoutAmountSfunc f = new GetPayoutAmountSfunc();
        f.setAmounts(amounts);
        f.setCashFlow(cashFlow);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>nw.get_payout_amount_sfunc</code> as a field.
     */
    public static Field<Long[]> getPayoutAmountSfunc(Long[] amounts, CashFlowRecord cashFlow) {
        GetPayoutAmountSfunc f = new GetPayoutAmountSfunc();
        f.setAmounts(amounts);
        f.setCashFlow(cashFlow);

        return f.asField();
    }

    /**
     * Get <code>nw.get_payout_amount_sfunc</code> as a field.
     */
    public static Field<Long[]> getPayoutAmountSfunc(Field<Long[]> amounts, Field<CashFlowRecord> cashFlow) {
        GetPayoutAmountSfunc f = new GetPayoutAmountSfunc();
        f.setAmounts(amounts);
        f.setCashFlow(cashFlow);

        return f.asField();
    }

    /**
     * Get <code>nw.get_payout_fee</code> as a field.
     */
    public static AggregateFunction<Long> getPayoutFee(CashFlowRecord __1) {
        GetPayoutFee f = new GetPayoutFee();
        f.set__1(__1);

        return f.asAggregateFunction();
    }

    /**
     * Get <code>nw.get_payout_fee</code> as a field.
     */
    public static AggregateFunction<Long> getPayoutFee(Field<CashFlowRecord> __1) {
        GetPayoutFee f = new GetPayoutFee();
        f.set__1(__1);

        return f.asAggregateFunction();
    }

    /**
     * Call <code>nw.get_payout_fee_sfunc</code>
     */
    public static Long[] getPayoutFeeSfunc(Configuration configuration, Long[] amounts, CashFlowRecord cashFlow) {
        GetPayoutFeeSfunc f = new GetPayoutFeeSfunc();
        f.setAmounts(amounts);
        f.setCashFlow(cashFlow);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>nw.get_payout_fee_sfunc</code> as a field.
     */
    public static Field<Long[]> getPayoutFeeSfunc(Long[] amounts, CashFlowRecord cashFlow) {
        GetPayoutFeeSfunc f = new GetPayoutFeeSfunc();
        f.setAmounts(amounts);
        f.setCashFlow(cashFlow);

        return f.asField();
    }

    /**
     * Get <code>nw.get_payout_fee_sfunc</code> as a field.
     */
    public static Field<Long[]> getPayoutFeeSfunc(Field<Long[]> amounts, Field<CashFlowRecord> cashFlow) {
        GetPayoutFeeSfunc f = new GetPayoutFeeSfunc();
        f.setAmounts(amounts);
        f.setCashFlow(cashFlow);

        return f.asField();
    }

    /**
     * Get <code>nw.get_payout_fixed_fee</code> as a field.
     */
    public static AggregateFunction<Long> getPayoutFixedFee(CashFlowRecord __1) {
        GetPayoutFixedFee f = new GetPayoutFixedFee();
        f.set__1(__1);

        return f.asAggregateFunction();
    }

    /**
     * Get <code>nw.get_payout_fixed_fee</code> as a field.
     */
    public static AggregateFunction<Long> getPayoutFixedFee(Field<CashFlowRecord> __1) {
        GetPayoutFixedFee f = new GetPayoutFixedFee();
        f.set__1(__1);

        return f.asAggregateFunction();
    }

    /**
     * Call <code>nw.get_payout_fixed_fee_sfunc</code>
     */
    public static Long[] getPayoutFixedFeeSfunc(Configuration configuration, Long[] amounts, CashFlowRecord cashFlow) {
        GetPayoutFixedFeeSfunc f = new GetPayoutFixedFeeSfunc();
        f.setAmounts(amounts);
        f.setCashFlow(cashFlow);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>nw.get_payout_fixed_fee_sfunc</code> as a field.
     */
    public static Field<Long[]> getPayoutFixedFeeSfunc(Long[] amounts, CashFlowRecord cashFlow) {
        GetPayoutFixedFeeSfunc f = new GetPayoutFixedFeeSfunc();
        f.setAmounts(amounts);
        f.setCashFlow(cashFlow);

        return f.asField();
    }

    /**
     * Get <code>nw.get_payout_fixed_fee_sfunc</code> as a field.
     */
    public static Field<Long[]> getPayoutFixedFeeSfunc(Field<Long[]> amounts, Field<CashFlowRecord> cashFlow) {
        GetPayoutFixedFeeSfunc f = new GetPayoutFixedFeeSfunc();
        f.setAmounts(amounts);
        f.setCashFlow(cashFlow);

        return f.asField();
    }

    /**
     * Get <code>nw.get_refund_amount</code> as a field.
     */
    public static AggregateFunction<Long> getRefundAmount(CashFlowRecord __1) {
        GetRefundAmount f = new GetRefundAmount();
        f.set__1(__1);

        return f.asAggregateFunction();
    }

    /**
     * Get <code>nw.get_refund_amount</code> as a field.
     */
    public static AggregateFunction<Long> getRefundAmount(Field<CashFlowRecord> __1) {
        GetRefundAmount f = new GetRefundAmount();
        f.set__1(__1);

        return f.asAggregateFunction();
    }

    /**
     * Call <code>nw.get_refund_amount_sfunc</code>
     */
    public static Long[] getRefundAmountSfunc(Configuration configuration, Long[] amounts, CashFlowRecord cashFlow) {
        GetRefundAmountSfunc f = new GetRefundAmountSfunc();
        f.setAmounts(amounts);
        f.setCashFlow(cashFlow);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>nw.get_refund_amount_sfunc</code> as a field.
     */
    public static Field<Long[]> getRefundAmountSfunc(Long[] amounts, CashFlowRecord cashFlow) {
        GetRefundAmountSfunc f = new GetRefundAmountSfunc();
        f.setAmounts(amounts);
        f.setCashFlow(cashFlow);

        return f.asField();
    }

    /**
     * Get <code>nw.get_refund_amount_sfunc</code> as a field.
     */
    public static Field<Long[]> getRefundAmountSfunc(Field<Long[]> amounts, Field<CashFlowRecord> cashFlow) {
        GetRefundAmountSfunc f = new GetRefundAmountSfunc();
        f.setAmounts(amounts);
        f.setCashFlow(cashFlow);

        return f.asField();
    }

    /**
     * Get <code>nw.get_refund_external_fee</code> as a field.
     */
    public static AggregateFunction<Long> getRefundExternalFee(CashFlowRecord __1) {
        GetRefundExternalFee f = new GetRefundExternalFee();
        f.set__1(__1);

        return f.asAggregateFunction();
    }

    /**
     * Get <code>nw.get_refund_external_fee</code> as a field.
     */
    public static AggregateFunction<Long> getRefundExternalFee(Field<CashFlowRecord> __1) {
        GetRefundExternalFee f = new GetRefundExternalFee();
        f.set__1(__1);

        return f.asAggregateFunction();
    }

    /**
     * Call <code>nw.get_refund_external_fee_sfunc</code>
     */
    public static Long[] getRefundExternalFeeSfunc(Configuration configuration, Long[] amounts, CashFlowRecord cashFlow) {
        GetRefundExternalFeeSfunc f = new GetRefundExternalFeeSfunc();
        f.setAmounts(amounts);
        f.setCashFlow(cashFlow);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>nw.get_refund_external_fee_sfunc</code> as a field.
     */
    public static Field<Long[]> getRefundExternalFeeSfunc(Long[] amounts, CashFlowRecord cashFlow) {
        GetRefundExternalFeeSfunc f = new GetRefundExternalFeeSfunc();
        f.setAmounts(amounts);
        f.setCashFlow(cashFlow);

        return f.asField();
    }

    /**
     * Get <code>nw.get_refund_external_fee_sfunc</code> as a field.
     */
    public static Field<Long[]> getRefundExternalFeeSfunc(Field<Long[]> amounts, Field<CashFlowRecord> cashFlow) {
        GetRefundExternalFeeSfunc f = new GetRefundExternalFeeSfunc();
        f.setAmounts(amounts);
        f.setCashFlow(cashFlow);

        return f.asField();
    }

    /**
     * Get <code>nw.get_refund_fee</code> as a field.
     */
    public static AggregateFunction<Long> getRefundFee(CashFlowRecord __1) {
        GetRefundFee f = new GetRefundFee();
        f.set__1(__1);

        return f.asAggregateFunction();
    }

    /**
     * Get <code>nw.get_refund_fee</code> as a field.
     */
    public static AggregateFunction<Long> getRefundFee(Field<CashFlowRecord> __1) {
        GetRefundFee f = new GetRefundFee();
        f.set__1(__1);

        return f.asAggregateFunction();
    }

    /**
     * Call <code>nw.get_refund_fee_sfunc</code>
     */
    public static Long[] getRefundFeeSfunc(Configuration configuration, Long[] amounts, CashFlowRecord cashFlow) {
        GetRefundFeeSfunc f = new GetRefundFeeSfunc();
        f.setAmounts(amounts);
        f.setCashFlow(cashFlow);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>nw.get_refund_fee_sfunc</code> as a field.
     */
    public static Field<Long[]> getRefundFeeSfunc(Long[] amounts, CashFlowRecord cashFlow) {
        GetRefundFeeSfunc f = new GetRefundFeeSfunc();
        f.setAmounts(amounts);
        f.setCashFlow(cashFlow);

        return f.asField();
    }

    /**
     * Get <code>nw.get_refund_fee_sfunc</code> as a field.
     */
    public static Field<Long[]> getRefundFeeSfunc(Field<Long[]> amounts, Field<CashFlowRecord> cashFlow) {
        GetRefundFeeSfunc f = new GetRefundFeeSfunc();
        f.setAmounts(amounts);
        f.setCashFlow(cashFlow);

        return f.asField();
    }

    /**
     * Get <code>nw.get_refund_provider_fee</code> as a field.
     */
    public static AggregateFunction<Long> getRefundProviderFee(CashFlowRecord __1) {
        GetRefundProviderFee f = new GetRefundProviderFee();
        f.set__1(__1);

        return f.asAggregateFunction();
    }

    /**
     * Get <code>nw.get_refund_provider_fee</code> as a field.
     */
    public static AggregateFunction<Long> getRefundProviderFee(Field<CashFlowRecord> __1) {
        GetRefundProviderFee f = new GetRefundProviderFee();
        f.set__1(__1);

        return f.asAggregateFunction();
    }

    /**
     * Call <code>nw.get_refund_provider_fee_sfunc</code>
     */
    public static Long[] getRefundProviderFeeSfunc(Configuration configuration, Long[] amounts, CashFlowRecord cashFlow) {
        GetRefundProviderFeeSfunc f = new GetRefundProviderFeeSfunc();
        f.setAmounts(amounts);
        f.setCashFlow(cashFlow);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>nw.get_refund_provider_fee_sfunc</code> as a field.
     */
    public static Field<Long[]> getRefundProviderFeeSfunc(Long[] amounts, CashFlowRecord cashFlow) {
        GetRefundProviderFeeSfunc f = new GetRefundProviderFeeSfunc();
        f.setAmounts(amounts);
        f.setCashFlow(cashFlow);

        return f.asField();
    }

    /**
     * Get <code>nw.get_refund_provider_fee_sfunc</code> as a field.
     */
    public static Field<Long[]> getRefundProviderFeeSfunc(Field<Long[]> amounts, Field<CashFlowRecord> cashFlow) {
        GetRefundProviderFeeSfunc f = new GetRefundProviderFeeSfunc();
        f.setAmounts(amounts);
        f.setCashFlow(cashFlow);

        return f.asField();
    }
}
