/*
 * This file is generated by jOOQ.
*/
package com.rbkmoney.newway.domain;


import com.rbkmoney.newway.domain.enums.CashFlowAccount;
import com.rbkmoney.newway.domain.enums.PaymentChangeType;
import com.rbkmoney.newway.domain.routines.CashflowSumFinalfunc1;
import com.rbkmoney.newway.domain.routines.CashflowSumFinalfunc2;
import com.rbkmoney.newway.domain.routines.GetAdjustmentAmount;
import com.rbkmoney.newway.domain.routines.GetAdjustmentAmountSfunc1;
import com.rbkmoney.newway.domain.routines.GetAdjustmentAmountSfunc2;
import com.rbkmoney.newway.domain.routines.GetAdjustmentExternalFee;
import com.rbkmoney.newway.domain.routines.GetAdjustmentExternalFeeSfunc1;
import com.rbkmoney.newway.domain.routines.GetAdjustmentExternalFeeSfunc2;
import com.rbkmoney.newway.domain.routines.GetAdjustmentFee;
import com.rbkmoney.newway.domain.routines.GetAdjustmentFeeSfunc1;
import com.rbkmoney.newway.domain.routines.GetAdjustmentFeeSfunc2;
import com.rbkmoney.newway.domain.routines.GetAdjustmentProviderFee;
import com.rbkmoney.newway.domain.routines.GetAdjustmentProviderFeeSfunc1;
import com.rbkmoney.newway.domain.routines.GetAdjustmentProviderFeeSfunc2;
import com.rbkmoney.newway.domain.routines.GetCashflowSum;
import com.rbkmoney.newway.domain.routines.GetPaymentAmount;
import com.rbkmoney.newway.domain.routines.GetPaymentAmountSfunc1;
import com.rbkmoney.newway.domain.routines.GetPaymentAmountSfunc2;
import com.rbkmoney.newway.domain.routines.GetPaymentExternalFee;
import com.rbkmoney.newway.domain.routines.GetPaymentExternalFeeSfunc1;
import com.rbkmoney.newway.domain.routines.GetPaymentExternalFeeSfunc2;
import com.rbkmoney.newway.domain.routines.GetPaymentFee;
import com.rbkmoney.newway.domain.routines.GetPaymentFeeSfunc1;
import com.rbkmoney.newway.domain.routines.GetPaymentFeeSfunc2;
import com.rbkmoney.newway.domain.routines.GetPaymentGuaranteeDeposit;
import com.rbkmoney.newway.domain.routines.GetPaymentGuaranteeDepositSfunc1;
import com.rbkmoney.newway.domain.routines.GetPaymentGuaranteeDepositSfunc2;
import com.rbkmoney.newway.domain.routines.GetPaymentProviderFee;
import com.rbkmoney.newway.domain.routines.GetPaymentProviderFeeSfunc1;
import com.rbkmoney.newway.domain.routines.GetPaymentProviderFeeSfunc2;
import com.rbkmoney.newway.domain.routines.GetPayoutAmount;
import com.rbkmoney.newway.domain.routines.GetPayoutAmountSfunc1;
import com.rbkmoney.newway.domain.routines.GetPayoutAmountSfunc2;
import com.rbkmoney.newway.domain.routines.GetPayoutFee;
import com.rbkmoney.newway.domain.routines.GetPayoutFeeSfunc1;
import com.rbkmoney.newway.domain.routines.GetPayoutFeeSfunc2;
import com.rbkmoney.newway.domain.routines.GetPayoutFixedFee;
import com.rbkmoney.newway.domain.routines.GetPayoutFixedFeeSfunc1;
import com.rbkmoney.newway.domain.routines.GetPayoutFixedFeeSfunc2;
import com.rbkmoney.newway.domain.routines.GetRefundAmount;
import com.rbkmoney.newway.domain.routines.GetRefundAmountSfunc1;
import com.rbkmoney.newway.domain.routines.GetRefundAmountSfunc2;
import com.rbkmoney.newway.domain.routines.GetRefundExternalFee;
import com.rbkmoney.newway.domain.routines.GetRefundExternalFeeSfunc1;
import com.rbkmoney.newway.domain.routines.GetRefundExternalFeeSfunc2;
import com.rbkmoney.newway.domain.routines.GetRefundFee;
import com.rbkmoney.newway.domain.routines.GetRefundFeeSfunc1;
import com.rbkmoney.newway.domain.routines.GetRefundFeeSfunc2;
import com.rbkmoney.newway.domain.routines.GetRefundProviderFee;
import com.rbkmoney.newway.domain.routines.GetRefundProviderFeeSfunc1;
import com.rbkmoney.newway.domain.routines.GetRefundProviderFeeSfunc2;
import com.rbkmoney.newway.domain.tables.records.CashFlowRecord;

import javax.annotation.Generated;

import org.jooq.AggregateFunction;
import org.jooq.Configuration;
import org.jooq.Field;


/**
 * Convenience access to all stored procedures and functions in nw
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Routines {

    /**
     * Call <code>nw.cashflow_sum_finalfunc</code>
     */
    public static Long cashflowSumFinalfunc1(Configuration configuration, Long[] amounts) {
        CashflowSumFinalfunc1 f = new CashflowSumFinalfunc1();
        f.setAmounts(amounts);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>nw.cashflow_sum_finalfunc</code> as a field.
     */
    public static Field<Long> cashflowSumFinalfunc1(Long[] amounts) {
        CashflowSumFinalfunc1 f = new CashflowSumFinalfunc1();
        f.setAmounts(amounts);

        return f.asField();
    }

    /**
     * Get <code>nw.cashflow_sum_finalfunc</code> as a field.
     */
    public static Field<Long> cashflowSumFinalfunc1(Field<Long[]> amounts) {
        CashflowSumFinalfunc1 f = new CashflowSumFinalfunc1();
        f.setAmounts(amounts);

        return f.asField();
    }

    /**
     * Call <code>nw.cashflow_sum_finalfunc</code>
     */
    public static Long cashflowSumFinalfunc2(Configuration configuration, Long amount) {
        CashflowSumFinalfunc2 f = new CashflowSumFinalfunc2();
        f.setAmount(amount);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>nw.cashflow_sum_finalfunc</code> as a field.
     */
    public static Field<Long> cashflowSumFinalfunc2(Long amount) {
        CashflowSumFinalfunc2 f = new CashflowSumFinalfunc2();
        f.setAmount(amount);

        return f.asField();
    }

    /**
     * Get <code>nw.cashflow_sum_finalfunc</code> as a field.
     */
    public static Field<Long> cashflowSumFinalfunc2(Field<Long> amount) {
        CashflowSumFinalfunc2 f = new CashflowSumFinalfunc2();
        f.setAmount(amount);

        return f.asField();
    }

    /**
     * Get <code>nw.get_adjustment_amount</code> as a field.
     */
    public static AggregateFunction<Long> getAdjustmentAmount(CashFlowRecord __1) {
        GetAdjustmentAmount f = new GetAdjustmentAmount();
        f.set__1(__1);

        return f.asAggregateFunction();
    }

    /**
     * Get <code>nw.get_adjustment_amount</code> as a field.
     */
    public static AggregateFunction<Long> getAdjustmentAmount(Field<CashFlowRecord> __1) {
        GetAdjustmentAmount f = new GetAdjustmentAmount();
        f.set__1(__1);

        return f.asAggregateFunction();
    }

    /**
     * Call <code>nw.get_adjustment_amount_sfunc</code>
     */
    public static Long[] getAdjustmentAmountSfunc1(Configuration configuration, Long[] amounts, CashFlowRecord cashFlow) {
        GetAdjustmentAmountSfunc1 f = new GetAdjustmentAmountSfunc1();
        f.setAmounts(amounts);
        f.setCashFlow(cashFlow);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>nw.get_adjustment_amount_sfunc</code> as a field.
     */
    public static Field<Long[]> getAdjustmentAmountSfunc1(Long[] amounts, CashFlowRecord cashFlow) {
        GetAdjustmentAmountSfunc1 f = new GetAdjustmentAmountSfunc1();
        f.setAmounts(amounts);
        f.setCashFlow(cashFlow);

        return f.asField();
    }

    /**
     * Get <code>nw.get_adjustment_amount_sfunc</code> as a field.
     */
    public static Field<Long[]> getAdjustmentAmountSfunc1(Field<Long[]> amounts, Field<CashFlowRecord> cashFlow) {
        GetAdjustmentAmountSfunc1 f = new GetAdjustmentAmountSfunc1();
        f.setAmounts(amounts);
        f.setCashFlow(cashFlow);

        return f.asField();
    }

    /**
     * Call <code>nw.get_adjustment_amount_sfunc</code>
     */
    public static Long getAdjustmentAmountSfunc2(Configuration configuration, Long amount, CashFlowRecord cashFlow) {
        GetAdjustmentAmountSfunc2 f = new GetAdjustmentAmountSfunc2();
        f.setAmount(amount);
        f.setCashFlow(cashFlow);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>nw.get_adjustment_amount_sfunc</code> as a field.
     */
    public static Field<Long> getAdjustmentAmountSfunc2(Long amount, CashFlowRecord cashFlow) {
        GetAdjustmentAmountSfunc2 f = new GetAdjustmentAmountSfunc2();
        f.setAmount(amount);
        f.setCashFlow(cashFlow);

        return f.asField();
    }

    /**
     * Get <code>nw.get_adjustment_amount_sfunc</code> as a field.
     */
    public static Field<Long> getAdjustmentAmountSfunc2(Field<Long> amount, Field<CashFlowRecord> cashFlow) {
        GetAdjustmentAmountSfunc2 f = new GetAdjustmentAmountSfunc2();
        f.setAmount(amount);
        f.setCashFlow(cashFlow);

        return f.asField();
    }

    /**
     * Get <code>nw.get_adjustment_external_fee</code> as a field.
     */
    public static AggregateFunction<Long> getAdjustmentExternalFee(CashFlowRecord __1) {
        GetAdjustmentExternalFee f = new GetAdjustmentExternalFee();
        f.set__1(__1);

        return f.asAggregateFunction();
    }

    /**
     * Get <code>nw.get_adjustment_external_fee</code> as a field.
     */
    public static AggregateFunction<Long> getAdjustmentExternalFee(Field<CashFlowRecord> __1) {
        GetAdjustmentExternalFee f = new GetAdjustmentExternalFee();
        f.set__1(__1);

        return f.asAggregateFunction();
    }

    /**
     * Call <code>nw.get_adjustment_external_fee_sfunc</code>
     */
    public static Long[] getAdjustmentExternalFeeSfunc1(Configuration configuration, Long[] amounts, CashFlowRecord cashFlow) {
        GetAdjustmentExternalFeeSfunc1 f = new GetAdjustmentExternalFeeSfunc1();
        f.setAmounts(amounts);
        f.setCashFlow(cashFlow);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>nw.get_adjustment_external_fee_sfunc</code> as a field.
     */
    public static Field<Long[]> getAdjustmentExternalFeeSfunc1(Long[] amounts, CashFlowRecord cashFlow) {
        GetAdjustmentExternalFeeSfunc1 f = new GetAdjustmentExternalFeeSfunc1();
        f.setAmounts(amounts);
        f.setCashFlow(cashFlow);

        return f.asField();
    }

    /**
     * Get <code>nw.get_adjustment_external_fee_sfunc</code> as a field.
     */
    public static Field<Long[]> getAdjustmentExternalFeeSfunc1(Field<Long[]> amounts, Field<CashFlowRecord> cashFlow) {
        GetAdjustmentExternalFeeSfunc1 f = new GetAdjustmentExternalFeeSfunc1();
        f.setAmounts(amounts);
        f.setCashFlow(cashFlow);

        return f.asField();
    }

    /**
     * Call <code>nw.get_adjustment_external_fee_sfunc</code>
     */
    public static Long getAdjustmentExternalFeeSfunc2(Configuration configuration, Long amount, CashFlowRecord cashFlow) {
        GetAdjustmentExternalFeeSfunc2 f = new GetAdjustmentExternalFeeSfunc2();
        f.setAmount(amount);
        f.setCashFlow(cashFlow);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>nw.get_adjustment_external_fee_sfunc</code> as a field.
     */
    public static Field<Long> getAdjustmentExternalFeeSfunc2(Long amount, CashFlowRecord cashFlow) {
        GetAdjustmentExternalFeeSfunc2 f = new GetAdjustmentExternalFeeSfunc2();
        f.setAmount(amount);
        f.setCashFlow(cashFlow);

        return f.asField();
    }

    /**
     * Get <code>nw.get_adjustment_external_fee_sfunc</code> as a field.
     */
    public static Field<Long> getAdjustmentExternalFeeSfunc2(Field<Long> amount, Field<CashFlowRecord> cashFlow) {
        GetAdjustmentExternalFeeSfunc2 f = new GetAdjustmentExternalFeeSfunc2();
        f.setAmount(amount);
        f.setCashFlow(cashFlow);

        return f.asField();
    }

    /**
     * Get <code>nw.get_adjustment_fee</code> as a field.
     */
    public static AggregateFunction<Long> getAdjustmentFee(CashFlowRecord __1) {
        GetAdjustmentFee f = new GetAdjustmentFee();
        f.set__1(__1);

        return f.asAggregateFunction();
    }

    /**
     * Get <code>nw.get_adjustment_fee</code> as a field.
     */
    public static AggregateFunction<Long> getAdjustmentFee(Field<CashFlowRecord> __1) {
        GetAdjustmentFee f = new GetAdjustmentFee();
        f.set__1(__1);

        return f.asAggregateFunction();
    }

    /**
     * Call <code>nw.get_adjustment_fee_sfunc</code>
     */
    public static Long[] getAdjustmentFeeSfunc1(Configuration configuration, Long[] amounts, CashFlowRecord cashFlow) {
        GetAdjustmentFeeSfunc1 f = new GetAdjustmentFeeSfunc1();
        f.setAmounts(amounts);
        f.setCashFlow(cashFlow);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>nw.get_adjustment_fee_sfunc</code> as a field.
     */
    public static Field<Long[]> getAdjustmentFeeSfunc1(Long[] amounts, CashFlowRecord cashFlow) {
        GetAdjustmentFeeSfunc1 f = new GetAdjustmentFeeSfunc1();
        f.setAmounts(amounts);
        f.setCashFlow(cashFlow);

        return f.asField();
    }

    /**
     * Get <code>nw.get_adjustment_fee_sfunc</code> as a field.
     */
    public static Field<Long[]> getAdjustmentFeeSfunc1(Field<Long[]> amounts, Field<CashFlowRecord> cashFlow) {
        GetAdjustmentFeeSfunc1 f = new GetAdjustmentFeeSfunc1();
        f.setAmounts(amounts);
        f.setCashFlow(cashFlow);

        return f.asField();
    }

    /**
     * Call <code>nw.get_adjustment_fee_sfunc</code>
     */
    public static Long getAdjustmentFeeSfunc2(Configuration configuration, Long amount, CashFlowRecord cashFlow) {
        GetAdjustmentFeeSfunc2 f = new GetAdjustmentFeeSfunc2();
        f.setAmount(amount);
        f.setCashFlow(cashFlow);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>nw.get_adjustment_fee_sfunc</code> as a field.
     */
    public static Field<Long> getAdjustmentFeeSfunc2(Long amount, CashFlowRecord cashFlow) {
        GetAdjustmentFeeSfunc2 f = new GetAdjustmentFeeSfunc2();
        f.setAmount(amount);
        f.setCashFlow(cashFlow);

        return f.asField();
    }

    /**
     * Get <code>nw.get_adjustment_fee_sfunc</code> as a field.
     */
    public static Field<Long> getAdjustmentFeeSfunc2(Field<Long> amount, Field<CashFlowRecord> cashFlow) {
        GetAdjustmentFeeSfunc2 f = new GetAdjustmentFeeSfunc2();
        f.setAmount(amount);
        f.setCashFlow(cashFlow);

        return f.asField();
    }

    /**
     * Get <code>nw.get_adjustment_provider_fee</code> as a field.
     */
    public static AggregateFunction<Long> getAdjustmentProviderFee(CashFlowRecord __1) {
        GetAdjustmentProviderFee f = new GetAdjustmentProviderFee();
        f.set__1(__1);

        return f.asAggregateFunction();
    }

    /**
     * Get <code>nw.get_adjustment_provider_fee</code> as a field.
     */
    public static AggregateFunction<Long> getAdjustmentProviderFee(Field<CashFlowRecord> __1) {
        GetAdjustmentProviderFee f = new GetAdjustmentProviderFee();
        f.set__1(__1);

        return f.asAggregateFunction();
    }

    /**
     * Call <code>nw.get_adjustment_provider_fee_sfunc</code>
     */
    public static Long[] getAdjustmentProviderFeeSfunc1(Configuration configuration, Long[] amounts, CashFlowRecord cashFlow) {
        GetAdjustmentProviderFeeSfunc1 f = new GetAdjustmentProviderFeeSfunc1();
        f.setAmounts(amounts);
        f.setCashFlow(cashFlow);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>nw.get_adjustment_provider_fee_sfunc</code> as a field.
     */
    public static Field<Long[]> getAdjustmentProviderFeeSfunc1(Long[] amounts, CashFlowRecord cashFlow) {
        GetAdjustmentProviderFeeSfunc1 f = new GetAdjustmentProviderFeeSfunc1();
        f.setAmounts(amounts);
        f.setCashFlow(cashFlow);

        return f.asField();
    }

    /**
     * Get <code>nw.get_adjustment_provider_fee_sfunc</code> as a field.
     */
    public static Field<Long[]> getAdjustmentProviderFeeSfunc1(Field<Long[]> amounts, Field<CashFlowRecord> cashFlow) {
        GetAdjustmentProviderFeeSfunc1 f = new GetAdjustmentProviderFeeSfunc1();
        f.setAmounts(amounts);
        f.setCashFlow(cashFlow);

        return f.asField();
    }

    /**
     * Call <code>nw.get_adjustment_provider_fee_sfunc</code>
     */
    public static Long getAdjustmentProviderFeeSfunc2(Configuration configuration, Long amount, CashFlowRecord cashFlow) {
        GetAdjustmentProviderFeeSfunc2 f = new GetAdjustmentProviderFeeSfunc2();
        f.setAmount(amount);
        f.setCashFlow(cashFlow);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>nw.get_adjustment_provider_fee_sfunc</code> as a field.
     */
    public static Field<Long> getAdjustmentProviderFeeSfunc2(Long amount, CashFlowRecord cashFlow) {
        GetAdjustmentProviderFeeSfunc2 f = new GetAdjustmentProviderFeeSfunc2();
        f.setAmount(amount);
        f.setCashFlow(cashFlow);

        return f.asField();
    }

    /**
     * Get <code>nw.get_adjustment_provider_fee_sfunc</code> as a field.
     */
    public static Field<Long> getAdjustmentProviderFeeSfunc2(Field<Long> amount, Field<CashFlowRecord> cashFlow) {
        GetAdjustmentProviderFeeSfunc2 f = new GetAdjustmentProviderFeeSfunc2();
        f.setAmount(amount);
        f.setCashFlow(cashFlow);

        return f.asField();
    }

    /**
     * Call <code>nw.get_cashflow_sum</code>
     */
    public static Long getCashflowSum(Configuration configuration, CashFlowRecord _CashFlow, PaymentChangeType objType, CashFlowAccount sourceAccountType, String[] sourceAccountTypeValues, CashFlowAccount destinationAccountType, String[] destinationAccountTypeValues) {
        GetCashflowSum f = new GetCashflowSum();
        f.set_CashFlow(_CashFlow);
        f.setObjType(objType);
        f.setSourceAccountType(sourceAccountType);
        f.setSourceAccountTypeValues(sourceAccountTypeValues);
        f.setDestinationAccountType(destinationAccountType);
        f.setDestinationAccountTypeValues(destinationAccountTypeValues);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>nw.get_cashflow_sum</code> as a field.
     */
    public static Field<Long> getCashflowSum(CashFlowRecord _CashFlow, PaymentChangeType objType, CashFlowAccount sourceAccountType, String[] sourceAccountTypeValues, CashFlowAccount destinationAccountType, String[] destinationAccountTypeValues) {
        GetCashflowSum f = new GetCashflowSum();
        f.set_CashFlow(_CashFlow);
        f.setObjType(objType);
        f.setSourceAccountType(sourceAccountType);
        f.setSourceAccountTypeValues(sourceAccountTypeValues);
        f.setDestinationAccountType(destinationAccountType);
        f.setDestinationAccountTypeValues(destinationAccountTypeValues);

        return f.asField();
    }

    /**
     * Get <code>nw.get_cashflow_sum</code> as a field.
     */
    public static Field<Long> getCashflowSum(Field<CashFlowRecord> _CashFlow, Field<PaymentChangeType> objType, Field<CashFlowAccount> sourceAccountType, Field<String[]> sourceAccountTypeValues, Field<CashFlowAccount> destinationAccountType, Field<String[]> destinationAccountTypeValues) {
        GetCashflowSum f = new GetCashflowSum();
        f.set_CashFlow(_CashFlow);
        f.setObjType(objType);
        f.setSourceAccountType(sourceAccountType);
        f.setSourceAccountTypeValues(sourceAccountTypeValues);
        f.setDestinationAccountType(destinationAccountType);
        f.setDestinationAccountTypeValues(destinationAccountTypeValues);

        return f.asField();
    }

    /**
     * Get <code>nw.get_payment_amount</code> as a field.
     */
    public static AggregateFunction<Long> getPaymentAmount(CashFlowRecord __1) {
        GetPaymentAmount f = new GetPaymentAmount();
        f.set__1(__1);

        return f.asAggregateFunction();
    }

    /**
     * Get <code>nw.get_payment_amount</code> as a field.
     */
    public static AggregateFunction<Long> getPaymentAmount(Field<CashFlowRecord> __1) {
        GetPaymentAmount f = new GetPaymentAmount();
        f.set__1(__1);

        return f.asAggregateFunction();
    }

    /**
     * Call <code>nw.get_payment_amount_sfunc</code>
     */
    public static Long[] getPaymentAmountSfunc1(Configuration configuration, Long[] amounts, CashFlowRecord cashFlow) {
        GetPaymentAmountSfunc1 f = new GetPaymentAmountSfunc1();
        f.setAmounts(amounts);
        f.setCashFlow(cashFlow);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>nw.get_payment_amount_sfunc</code> as a field.
     */
    public static Field<Long[]> getPaymentAmountSfunc1(Long[] amounts, CashFlowRecord cashFlow) {
        GetPaymentAmountSfunc1 f = new GetPaymentAmountSfunc1();
        f.setAmounts(amounts);
        f.setCashFlow(cashFlow);

        return f.asField();
    }

    /**
     * Get <code>nw.get_payment_amount_sfunc</code> as a field.
     */
    public static Field<Long[]> getPaymentAmountSfunc1(Field<Long[]> amounts, Field<CashFlowRecord> cashFlow) {
        GetPaymentAmountSfunc1 f = new GetPaymentAmountSfunc1();
        f.setAmounts(amounts);
        f.setCashFlow(cashFlow);

        return f.asField();
    }

    /**
     * Call <code>nw.get_payment_amount_sfunc</code>
     */
    public static Long getPaymentAmountSfunc2(Configuration configuration, Long amount, CashFlowRecord cashFlow) {
        GetPaymentAmountSfunc2 f = new GetPaymentAmountSfunc2();
        f.setAmount(amount);
        f.setCashFlow(cashFlow);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>nw.get_payment_amount_sfunc</code> as a field.
     */
    public static Field<Long> getPaymentAmountSfunc2(Long amount, CashFlowRecord cashFlow) {
        GetPaymentAmountSfunc2 f = new GetPaymentAmountSfunc2();
        f.setAmount(amount);
        f.setCashFlow(cashFlow);

        return f.asField();
    }

    /**
     * Get <code>nw.get_payment_amount_sfunc</code> as a field.
     */
    public static Field<Long> getPaymentAmountSfunc2(Field<Long> amount, Field<CashFlowRecord> cashFlow) {
        GetPaymentAmountSfunc2 f = new GetPaymentAmountSfunc2();
        f.setAmount(amount);
        f.setCashFlow(cashFlow);

        return f.asField();
    }

    /**
     * Get <code>nw.get_payment_external_fee</code> as a field.
     */
    public static AggregateFunction<Long> getPaymentExternalFee(CashFlowRecord __1) {
        GetPaymentExternalFee f = new GetPaymentExternalFee();
        f.set__1(__1);

        return f.asAggregateFunction();
    }

    /**
     * Get <code>nw.get_payment_external_fee</code> as a field.
     */
    public static AggregateFunction<Long> getPaymentExternalFee(Field<CashFlowRecord> __1) {
        GetPaymentExternalFee f = new GetPaymentExternalFee();
        f.set__1(__1);

        return f.asAggregateFunction();
    }

    /**
     * Call <code>nw.get_payment_external_fee_sfunc</code>
     */
    public static Long[] getPaymentExternalFeeSfunc1(Configuration configuration, Long[] amounts, CashFlowRecord cashFlow) {
        GetPaymentExternalFeeSfunc1 f = new GetPaymentExternalFeeSfunc1();
        f.setAmounts(amounts);
        f.setCashFlow(cashFlow);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>nw.get_payment_external_fee_sfunc</code> as a field.
     */
    public static Field<Long[]> getPaymentExternalFeeSfunc1(Long[] amounts, CashFlowRecord cashFlow) {
        GetPaymentExternalFeeSfunc1 f = new GetPaymentExternalFeeSfunc1();
        f.setAmounts(amounts);
        f.setCashFlow(cashFlow);

        return f.asField();
    }

    /**
     * Get <code>nw.get_payment_external_fee_sfunc</code> as a field.
     */
    public static Field<Long[]> getPaymentExternalFeeSfunc1(Field<Long[]> amounts, Field<CashFlowRecord> cashFlow) {
        GetPaymentExternalFeeSfunc1 f = new GetPaymentExternalFeeSfunc1();
        f.setAmounts(amounts);
        f.setCashFlow(cashFlow);

        return f.asField();
    }

    /**
     * Call <code>nw.get_payment_external_fee_sfunc</code>
     */
    public static Long getPaymentExternalFeeSfunc2(Configuration configuration, Long amount, CashFlowRecord cashFlow) {
        GetPaymentExternalFeeSfunc2 f = new GetPaymentExternalFeeSfunc2();
        f.setAmount(amount);
        f.setCashFlow(cashFlow);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>nw.get_payment_external_fee_sfunc</code> as a field.
     */
    public static Field<Long> getPaymentExternalFeeSfunc2(Long amount, CashFlowRecord cashFlow) {
        GetPaymentExternalFeeSfunc2 f = new GetPaymentExternalFeeSfunc2();
        f.setAmount(amount);
        f.setCashFlow(cashFlow);

        return f.asField();
    }

    /**
     * Get <code>nw.get_payment_external_fee_sfunc</code> as a field.
     */
    public static Field<Long> getPaymentExternalFeeSfunc2(Field<Long> amount, Field<CashFlowRecord> cashFlow) {
        GetPaymentExternalFeeSfunc2 f = new GetPaymentExternalFeeSfunc2();
        f.setAmount(amount);
        f.setCashFlow(cashFlow);

        return f.asField();
    }

    /**
     * Get <code>nw.get_payment_fee</code> as a field.
     */
    public static AggregateFunction<Long> getPaymentFee(CashFlowRecord __1) {
        GetPaymentFee f = new GetPaymentFee();
        f.set__1(__1);

        return f.asAggregateFunction();
    }

    /**
     * Get <code>nw.get_payment_fee</code> as a field.
     */
    public static AggregateFunction<Long> getPaymentFee(Field<CashFlowRecord> __1) {
        GetPaymentFee f = new GetPaymentFee();
        f.set__1(__1);

        return f.asAggregateFunction();
    }

    /**
     * Call <code>nw.get_payment_fee_sfunc</code>
     */
    public static Long[] getPaymentFeeSfunc1(Configuration configuration, Long[] amounts, CashFlowRecord cashFlow) {
        GetPaymentFeeSfunc1 f = new GetPaymentFeeSfunc1();
        f.setAmounts(amounts);
        f.setCashFlow(cashFlow);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>nw.get_payment_fee_sfunc</code> as a field.
     */
    public static Field<Long[]> getPaymentFeeSfunc1(Long[] amounts, CashFlowRecord cashFlow) {
        GetPaymentFeeSfunc1 f = new GetPaymentFeeSfunc1();
        f.setAmounts(amounts);
        f.setCashFlow(cashFlow);

        return f.asField();
    }

    /**
     * Get <code>nw.get_payment_fee_sfunc</code> as a field.
     */
    public static Field<Long[]> getPaymentFeeSfunc1(Field<Long[]> amounts, Field<CashFlowRecord> cashFlow) {
        GetPaymentFeeSfunc1 f = new GetPaymentFeeSfunc1();
        f.setAmounts(amounts);
        f.setCashFlow(cashFlow);

        return f.asField();
    }

    /**
     * Call <code>nw.get_payment_fee_sfunc</code>
     */
    public static Long getPaymentFeeSfunc2(Configuration configuration, Long amount, CashFlowRecord cashFlow) {
        GetPaymentFeeSfunc2 f = new GetPaymentFeeSfunc2();
        f.setAmount(amount);
        f.setCashFlow(cashFlow);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>nw.get_payment_fee_sfunc</code> as a field.
     */
    public static Field<Long> getPaymentFeeSfunc2(Long amount, CashFlowRecord cashFlow) {
        GetPaymentFeeSfunc2 f = new GetPaymentFeeSfunc2();
        f.setAmount(amount);
        f.setCashFlow(cashFlow);

        return f.asField();
    }

    /**
     * Get <code>nw.get_payment_fee_sfunc</code> as a field.
     */
    public static Field<Long> getPaymentFeeSfunc2(Field<Long> amount, Field<CashFlowRecord> cashFlow) {
        GetPaymentFeeSfunc2 f = new GetPaymentFeeSfunc2();
        f.setAmount(amount);
        f.setCashFlow(cashFlow);

        return f.asField();
    }

    /**
     * Get <code>nw.get_payment_guarantee_deposit</code> as a field.
     */
    public static AggregateFunction<Long> getPaymentGuaranteeDeposit(CashFlowRecord __1) {
        GetPaymentGuaranteeDeposit f = new GetPaymentGuaranteeDeposit();
        f.set__1(__1);

        return f.asAggregateFunction();
    }

    /**
     * Get <code>nw.get_payment_guarantee_deposit</code> as a field.
     */
    public static AggregateFunction<Long> getPaymentGuaranteeDeposit(Field<CashFlowRecord> __1) {
        GetPaymentGuaranteeDeposit f = new GetPaymentGuaranteeDeposit();
        f.set__1(__1);

        return f.asAggregateFunction();
    }

    /**
     * Call <code>nw.get_payment_guarantee_deposit_sfunc</code>
     */
    public static Long[] getPaymentGuaranteeDepositSfunc1(Configuration configuration, Long[] amounts, CashFlowRecord cashFlow) {
        GetPaymentGuaranteeDepositSfunc1 f = new GetPaymentGuaranteeDepositSfunc1();
        f.setAmounts(amounts);
        f.setCashFlow(cashFlow);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>nw.get_payment_guarantee_deposit_sfunc</code> as a field.
     */
    public static Field<Long[]> getPaymentGuaranteeDepositSfunc1(Long[] amounts, CashFlowRecord cashFlow) {
        GetPaymentGuaranteeDepositSfunc1 f = new GetPaymentGuaranteeDepositSfunc1();
        f.setAmounts(amounts);
        f.setCashFlow(cashFlow);

        return f.asField();
    }

    /**
     * Get <code>nw.get_payment_guarantee_deposit_sfunc</code> as a field.
     */
    public static Field<Long[]> getPaymentGuaranteeDepositSfunc1(Field<Long[]> amounts, Field<CashFlowRecord> cashFlow) {
        GetPaymentGuaranteeDepositSfunc1 f = new GetPaymentGuaranteeDepositSfunc1();
        f.setAmounts(amounts);
        f.setCashFlow(cashFlow);

        return f.asField();
    }

    /**
     * Call <code>nw.get_payment_guarantee_deposit_sfunc</code>
     */
    public static Long getPaymentGuaranteeDepositSfunc2(Configuration configuration, Long amount, CashFlowRecord cashFlow) {
        GetPaymentGuaranteeDepositSfunc2 f = new GetPaymentGuaranteeDepositSfunc2();
        f.setAmount(amount);
        f.setCashFlow(cashFlow);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>nw.get_payment_guarantee_deposit_sfunc</code> as a field.
     */
    public static Field<Long> getPaymentGuaranteeDepositSfunc2(Long amount, CashFlowRecord cashFlow) {
        GetPaymentGuaranteeDepositSfunc2 f = new GetPaymentGuaranteeDepositSfunc2();
        f.setAmount(amount);
        f.setCashFlow(cashFlow);

        return f.asField();
    }

    /**
     * Get <code>nw.get_payment_guarantee_deposit_sfunc</code> as a field.
     */
    public static Field<Long> getPaymentGuaranteeDepositSfunc2(Field<Long> amount, Field<CashFlowRecord> cashFlow) {
        GetPaymentGuaranteeDepositSfunc2 f = new GetPaymentGuaranteeDepositSfunc2();
        f.setAmount(amount);
        f.setCashFlow(cashFlow);

        return f.asField();
    }

    /**
     * Get <code>nw.get_payment_provider_fee</code> as a field.
     */
    public static AggregateFunction<Long> getPaymentProviderFee(CashFlowRecord __1) {
        GetPaymentProviderFee f = new GetPaymentProviderFee();
        f.set__1(__1);

        return f.asAggregateFunction();
    }

    /**
     * Get <code>nw.get_payment_provider_fee</code> as a field.
     */
    public static AggregateFunction<Long> getPaymentProviderFee(Field<CashFlowRecord> __1) {
        GetPaymentProviderFee f = new GetPaymentProviderFee();
        f.set__1(__1);

        return f.asAggregateFunction();
    }

    /**
     * Call <code>nw.get_payment_provider_fee_sfunc</code>
     */
    public static Long[] getPaymentProviderFeeSfunc1(Configuration configuration, Long[] amounts, CashFlowRecord cashFlow) {
        GetPaymentProviderFeeSfunc1 f = new GetPaymentProviderFeeSfunc1();
        f.setAmounts(amounts);
        f.setCashFlow(cashFlow);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>nw.get_payment_provider_fee_sfunc</code> as a field.
     */
    public static Field<Long[]> getPaymentProviderFeeSfunc1(Long[] amounts, CashFlowRecord cashFlow) {
        GetPaymentProviderFeeSfunc1 f = new GetPaymentProviderFeeSfunc1();
        f.setAmounts(amounts);
        f.setCashFlow(cashFlow);

        return f.asField();
    }

    /**
     * Get <code>nw.get_payment_provider_fee_sfunc</code> as a field.
     */
    public static Field<Long[]> getPaymentProviderFeeSfunc1(Field<Long[]> amounts, Field<CashFlowRecord> cashFlow) {
        GetPaymentProviderFeeSfunc1 f = new GetPaymentProviderFeeSfunc1();
        f.setAmounts(amounts);
        f.setCashFlow(cashFlow);

        return f.asField();
    }

    /**
     * Call <code>nw.get_payment_provider_fee_sfunc</code>
     */
    public static Long getPaymentProviderFeeSfunc2(Configuration configuration, Long amount, CashFlowRecord cashFlow) {
        GetPaymentProviderFeeSfunc2 f = new GetPaymentProviderFeeSfunc2();
        f.setAmount(amount);
        f.setCashFlow(cashFlow);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>nw.get_payment_provider_fee_sfunc</code> as a field.
     */
    public static Field<Long> getPaymentProviderFeeSfunc2(Long amount, CashFlowRecord cashFlow) {
        GetPaymentProviderFeeSfunc2 f = new GetPaymentProviderFeeSfunc2();
        f.setAmount(amount);
        f.setCashFlow(cashFlow);

        return f.asField();
    }

    /**
     * Get <code>nw.get_payment_provider_fee_sfunc</code> as a field.
     */
    public static Field<Long> getPaymentProviderFeeSfunc2(Field<Long> amount, Field<CashFlowRecord> cashFlow) {
        GetPaymentProviderFeeSfunc2 f = new GetPaymentProviderFeeSfunc2();
        f.setAmount(amount);
        f.setCashFlow(cashFlow);

        return f.asField();
    }

    /**
     * Get <code>nw.get_payout_amount</code> as a field.
     */
    public static AggregateFunction<Long> getPayoutAmount(CashFlowRecord __1) {
        GetPayoutAmount f = new GetPayoutAmount();
        f.set__1(__1);

        return f.asAggregateFunction();
    }

    /**
     * Get <code>nw.get_payout_amount</code> as a field.
     */
    public static AggregateFunction<Long> getPayoutAmount(Field<CashFlowRecord> __1) {
        GetPayoutAmount f = new GetPayoutAmount();
        f.set__1(__1);

        return f.asAggregateFunction();
    }

    /**
     * Call <code>nw.get_payout_amount_sfunc</code>
     */
    public static Long[] getPayoutAmountSfunc1(Configuration configuration, Long[] amounts, CashFlowRecord cashFlow) {
        GetPayoutAmountSfunc1 f = new GetPayoutAmountSfunc1();
        f.setAmounts(amounts);
        f.setCashFlow(cashFlow);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>nw.get_payout_amount_sfunc</code> as a field.
     */
    public static Field<Long[]> getPayoutAmountSfunc1(Long[] amounts, CashFlowRecord cashFlow) {
        GetPayoutAmountSfunc1 f = new GetPayoutAmountSfunc1();
        f.setAmounts(amounts);
        f.setCashFlow(cashFlow);

        return f.asField();
    }

    /**
     * Get <code>nw.get_payout_amount_sfunc</code> as a field.
     */
    public static Field<Long[]> getPayoutAmountSfunc1(Field<Long[]> amounts, Field<CashFlowRecord> cashFlow) {
        GetPayoutAmountSfunc1 f = new GetPayoutAmountSfunc1();
        f.setAmounts(amounts);
        f.setCashFlow(cashFlow);

        return f.asField();
    }

    /**
     * Call <code>nw.get_payout_amount_sfunc</code>
     */
    public static Long getPayoutAmountSfunc2(Configuration configuration, Long amount, CashFlowRecord cashFlow) {
        GetPayoutAmountSfunc2 f = new GetPayoutAmountSfunc2();
        f.setAmount(amount);
        f.setCashFlow(cashFlow);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>nw.get_payout_amount_sfunc</code> as a field.
     */
    public static Field<Long> getPayoutAmountSfunc2(Long amount, CashFlowRecord cashFlow) {
        GetPayoutAmountSfunc2 f = new GetPayoutAmountSfunc2();
        f.setAmount(amount);
        f.setCashFlow(cashFlow);

        return f.asField();
    }

    /**
     * Get <code>nw.get_payout_amount_sfunc</code> as a field.
     */
    public static Field<Long> getPayoutAmountSfunc2(Field<Long> amount, Field<CashFlowRecord> cashFlow) {
        GetPayoutAmountSfunc2 f = new GetPayoutAmountSfunc2();
        f.setAmount(amount);
        f.setCashFlow(cashFlow);

        return f.asField();
    }

    /**
     * Get <code>nw.get_payout_fee</code> as a field.
     */
    public static AggregateFunction<Long> getPayoutFee(CashFlowRecord __1) {
        GetPayoutFee f = new GetPayoutFee();
        f.set__1(__1);

        return f.asAggregateFunction();
    }

    /**
     * Get <code>nw.get_payout_fee</code> as a field.
     */
    public static AggregateFunction<Long> getPayoutFee(Field<CashFlowRecord> __1) {
        GetPayoutFee f = new GetPayoutFee();
        f.set__1(__1);

        return f.asAggregateFunction();
    }

    /**
     * Call <code>nw.get_payout_fee_sfunc</code>
     */
    public static Long[] getPayoutFeeSfunc1(Configuration configuration, Long[] amounts, CashFlowRecord cashFlow) {
        GetPayoutFeeSfunc1 f = new GetPayoutFeeSfunc1();
        f.setAmounts(amounts);
        f.setCashFlow(cashFlow);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>nw.get_payout_fee_sfunc</code> as a field.
     */
    public static Field<Long[]> getPayoutFeeSfunc1(Long[] amounts, CashFlowRecord cashFlow) {
        GetPayoutFeeSfunc1 f = new GetPayoutFeeSfunc1();
        f.setAmounts(amounts);
        f.setCashFlow(cashFlow);

        return f.asField();
    }

    /**
     * Get <code>nw.get_payout_fee_sfunc</code> as a field.
     */
    public static Field<Long[]> getPayoutFeeSfunc1(Field<Long[]> amounts, Field<CashFlowRecord> cashFlow) {
        GetPayoutFeeSfunc1 f = new GetPayoutFeeSfunc1();
        f.setAmounts(amounts);
        f.setCashFlow(cashFlow);

        return f.asField();
    }

    /**
     * Call <code>nw.get_payout_fee_sfunc</code>
     */
    public static Long getPayoutFeeSfunc2(Configuration configuration, Long amount, CashFlowRecord cashFlow) {
        GetPayoutFeeSfunc2 f = new GetPayoutFeeSfunc2();
        f.setAmount(amount);
        f.setCashFlow(cashFlow);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>nw.get_payout_fee_sfunc</code> as a field.
     */
    public static Field<Long> getPayoutFeeSfunc2(Long amount, CashFlowRecord cashFlow) {
        GetPayoutFeeSfunc2 f = new GetPayoutFeeSfunc2();
        f.setAmount(amount);
        f.setCashFlow(cashFlow);

        return f.asField();
    }

    /**
     * Get <code>nw.get_payout_fee_sfunc</code> as a field.
     */
    public static Field<Long> getPayoutFeeSfunc2(Field<Long> amount, Field<CashFlowRecord> cashFlow) {
        GetPayoutFeeSfunc2 f = new GetPayoutFeeSfunc2();
        f.setAmount(amount);
        f.setCashFlow(cashFlow);

        return f.asField();
    }

    /**
     * Get <code>nw.get_payout_fixed_fee</code> as a field.
     */
    public static AggregateFunction<Long> getPayoutFixedFee(CashFlowRecord __1) {
        GetPayoutFixedFee f = new GetPayoutFixedFee();
        f.set__1(__1);

        return f.asAggregateFunction();
    }

    /**
     * Get <code>nw.get_payout_fixed_fee</code> as a field.
     */
    public static AggregateFunction<Long> getPayoutFixedFee(Field<CashFlowRecord> __1) {
        GetPayoutFixedFee f = new GetPayoutFixedFee();
        f.set__1(__1);

        return f.asAggregateFunction();
    }

    /**
     * Call <code>nw.get_payout_fixed_fee_sfunc</code>
     */
    public static Long[] getPayoutFixedFeeSfunc1(Configuration configuration, Long[] amounts, CashFlowRecord cashFlow) {
        GetPayoutFixedFeeSfunc1 f = new GetPayoutFixedFeeSfunc1();
        f.setAmounts(amounts);
        f.setCashFlow(cashFlow);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>nw.get_payout_fixed_fee_sfunc</code> as a field.
     */
    public static Field<Long[]> getPayoutFixedFeeSfunc1(Long[] amounts, CashFlowRecord cashFlow) {
        GetPayoutFixedFeeSfunc1 f = new GetPayoutFixedFeeSfunc1();
        f.setAmounts(amounts);
        f.setCashFlow(cashFlow);

        return f.asField();
    }

    /**
     * Get <code>nw.get_payout_fixed_fee_sfunc</code> as a field.
     */
    public static Field<Long[]> getPayoutFixedFeeSfunc1(Field<Long[]> amounts, Field<CashFlowRecord> cashFlow) {
        GetPayoutFixedFeeSfunc1 f = new GetPayoutFixedFeeSfunc1();
        f.setAmounts(amounts);
        f.setCashFlow(cashFlow);

        return f.asField();
    }

    /**
     * Call <code>nw.get_payout_fixed_fee_sfunc</code>
     */
    public static Long getPayoutFixedFeeSfunc2(Configuration configuration, Long amount, CashFlowRecord cashFlow) {
        GetPayoutFixedFeeSfunc2 f = new GetPayoutFixedFeeSfunc2();
        f.setAmount(amount);
        f.setCashFlow(cashFlow);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>nw.get_payout_fixed_fee_sfunc</code> as a field.
     */
    public static Field<Long> getPayoutFixedFeeSfunc2(Long amount, CashFlowRecord cashFlow) {
        GetPayoutFixedFeeSfunc2 f = new GetPayoutFixedFeeSfunc2();
        f.setAmount(amount);
        f.setCashFlow(cashFlow);

        return f.asField();
    }

    /**
     * Get <code>nw.get_payout_fixed_fee_sfunc</code> as a field.
     */
    public static Field<Long> getPayoutFixedFeeSfunc2(Field<Long> amount, Field<CashFlowRecord> cashFlow) {
        GetPayoutFixedFeeSfunc2 f = new GetPayoutFixedFeeSfunc2();
        f.setAmount(amount);
        f.setCashFlow(cashFlow);

        return f.asField();
    }

    /**
     * Get <code>nw.get_refund_amount</code> as a field.
     */
    public static AggregateFunction<Long> getRefundAmount(CashFlowRecord __1) {
        GetRefundAmount f = new GetRefundAmount();
        f.set__1(__1);

        return f.asAggregateFunction();
    }

    /**
     * Get <code>nw.get_refund_amount</code> as a field.
     */
    public static AggregateFunction<Long> getRefundAmount(Field<CashFlowRecord> __1) {
        GetRefundAmount f = new GetRefundAmount();
        f.set__1(__1);

        return f.asAggregateFunction();
    }

    /**
     * Call <code>nw.get_refund_amount_sfunc</code>
     */
    public static Long[] getRefundAmountSfunc1(Configuration configuration, Long[] amounts, CashFlowRecord cashFlow) {
        GetRefundAmountSfunc1 f = new GetRefundAmountSfunc1();
        f.setAmounts(amounts);
        f.setCashFlow(cashFlow);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>nw.get_refund_amount_sfunc</code> as a field.
     */
    public static Field<Long[]> getRefundAmountSfunc1(Long[] amounts, CashFlowRecord cashFlow) {
        GetRefundAmountSfunc1 f = new GetRefundAmountSfunc1();
        f.setAmounts(amounts);
        f.setCashFlow(cashFlow);

        return f.asField();
    }

    /**
     * Get <code>nw.get_refund_amount_sfunc</code> as a field.
     */
    public static Field<Long[]> getRefundAmountSfunc1(Field<Long[]> amounts, Field<CashFlowRecord> cashFlow) {
        GetRefundAmountSfunc1 f = new GetRefundAmountSfunc1();
        f.setAmounts(amounts);
        f.setCashFlow(cashFlow);

        return f.asField();
    }

    /**
     * Call <code>nw.get_refund_amount_sfunc</code>
     */
    public static Long getRefundAmountSfunc2(Configuration configuration, Long amount, CashFlowRecord cashFlow) {
        GetRefundAmountSfunc2 f = new GetRefundAmountSfunc2();
        f.setAmount(amount);
        f.setCashFlow(cashFlow);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>nw.get_refund_amount_sfunc</code> as a field.
     */
    public static Field<Long> getRefundAmountSfunc2(Long amount, CashFlowRecord cashFlow) {
        GetRefundAmountSfunc2 f = new GetRefundAmountSfunc2();
        f.setAmount(amount);
        f.setCashFlow(cashFlow);

        return f.asField();
    }

    /**
     * Get <code>nw.get_refund_amount_sfunc</code> as a field.
     */
    public static Field<Long> getRefundAmountSfunc2(Field<Long> amount, Field<CashFlowRecord> cashFlow) {
        GetRefundAmountSfunc2 f = new GetRefundAmountSfunc2();
        f.setAmount(amount);
        f.setCashFlow(cashFlow);

        return f.asField();
    }

    /**
     * Get <code>nw.get_refund_external_fee</code> as a field.
     */
    public static AggregateFunction<Long> getRefundExternalFee(CashFlowRecord __1) {
        GetRefundExternalFee f = new GetRefundExternalFee();
        f.set__1(__1);

        return f.asAggregateFunction();
    }

    /**
     * Get <code>nw.get_refund_external_fee</code> as a field.
     */
    public static AggregateFunction<Long> getRefundExternalFee(Field<CashFlowRecord> __1) {
        GetRefundExternalFee f = new GetRefundExternalFee();
        f.set__1(__1);

        return f.asAggregateFunction();
    }

    /**
     * Call <code>nw.get_refund_external_fee_sfunc</code>
     */
    public static Long[] getRefundExternalFeeSfunc1(Configuration configuration, Long[] amounts, CashFlowRecord cashFlow) {
        GetRefundExternalFeeSfunc1 f = new GetRefundExternalFeeSfunc1();
        f.setAmounts(amounts);
        f.setCashFlow(cashFlow);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>nw.get_refund_external_fee_sfunc</code> as a field.
     */
    public static Field<Long[]> getRefundExternalFeeSfunc1(Long[] amounts, CashFlowRecord cashFlow) {
        GetRefundExternalFeeSfunc1 f = new GetRefundExternalFeeSfunc1();
        f.setAmounts(amounts);
        f.setCashFlow(cashFlow);

        return f.asField();
    }

    /**
     * Get <code>nw.get_refund_external_fee_sfunc</code> as a field.
     */
    public static Field<Long[]> getRefundExternalFeeSfunc1(Field<Long[]> amounts, Field<CashFlowRecord> cashFlow) {
        GetRefundExternalFeeSfunc1 f = new GetRefundExternalFeeSfunc1();
        f.setAmounts(amounts);
        f.setCashFlow(cashFlow);

        return f.asField();
    }

    /**
     * Call <code>nw.get_refund_external_fee_sfunc</code>
     */
    public static Long getRefundExternalFeeSfunc2(Configuration configuration, Long amount, CashFlowRecord cashFlow) {
        GetRefundExternalFeeSfunc2 f = new GetRefundExternalFeeSfunc2();
        f.setAmount(amount);
        f.setCashFlow(cashFlow);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>nw.get_refund_external_fee_sfunc</code> as a field.
     */
    public static Field<Long> getRefundExternalFeeSfunc2(Long amount, CashFlowRecord cashFlow) {
        GetRefundExternalFeeSfunc2 f = new GetRefundExternalFeeSfunc2();
        f.setAmount(amount);
        f.setCashFlow(cashFlow);

        return f.asField();
    }

    /**
     * Get <code>nw.get_refund_external_fee_sfunc</code> as a field.
     */
    public static Field<Long> getRefundExternalFeeSfunc2(Field<Long> amount, Field<CashFlowRecord> cashFlow) {
        GetRefundExternalFeeSfunc2 f = new GetRefundExternalFeeSfunc2();
        f.setAmount(amount);
        f.setCashFlow(cashFlow);

        return f.asField();
    }

    /**
     * Get <code>nw.get_refund_fee</code> as a field.
     */
    public static AggregateFunction<Long> getRefundFee(CashFlowRecord __1) {
        GetRefundFee f = new GetRefundFee();
        f.set__1(__1);

        return f.asAggregateFunction();
    }

    /**
     * Get <code>nw.get_refund_fee</code> as a field.
     */
    public static AggregateFunction<Long> getRefundFee(Field<CashFlowRecord> __1) {
        GetRefundFee f = new GetRefundFee();
        f.set__1(__1);

        return f.asAggregateFunction();
    }

    /**
     * Call <code>nw.get_refund_fee_sfunc</code>
     */
    public static Long[] getRefundFeeSfunc1(Configuration configuration, Long[] amounts, CashFlowRecord cashFlow) {
        GetRefundFeeSfunc1 f = new GetRefundFeeSfunc1();
        f.setAmounts(amounts);
        f.setCashFlow(cashFlow);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>nw.get_refund_fee_sfunc</code> as a field.
     */
    public static Field<Long[]> getRefundFeeSfunc1(Long[] amounts, CashFlowRecord cashFlow) {
        GetRefundFeeSfunc1 f = new GetRefundFeeSfunc1();
        f.setAmounts(amounts);
        f.setCashFlow(cashFlow);

        return f.asField();
    }

    /**
     * Get <code>nw.get_refund_fee_sfunc</code> as a field.
     */
    public static Field<Long[]> getRefundFeeSfunc1(Field<Long[]> amounts, Field<CashFlowRecord> cashFlow) {
        GetRefundFeeSfunc1 f = new GetRefundFeeSfunc1();
        f.setAmounts(amounts);
        f.setCashFlow(cashFlow);

        return f.asField();
    }

    /**
     * Call <code>nw.get_refund_fee_sfunc</code>
     */
    public static Long getRefundFeeSfunc2(Configuration configuration, Long amount, CashFlowRecord cashFlow) {
        GetRefundFeeSfunc2 f = new GetRefundFeeSfunc2();
        f.setAmount(amount);
        f.setCashFlow(cashFlow);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>nw.get_refund_fee_sfunc</code> as a field.
     */
    public static Field<Long> getRefundFeeSfunc2(Long amount, CashFlowRecord cashFlow) {
        GetRefundFeeSfunc2 f = new GetRefundFeeSfunc2();
        f.setAmount(amount);
        f.setCashFlow(cashFlow);

        return f.asField();
    }

    /**
     * Get <code>nw.get_refund_fee_sfunc</code> as a field.
     */
    public static Field<Long> getRefundFeeSfunc2(Field<Long> amount, Field<CashFlowRecord> cashFlow) {
        GetRefundFeeSfunc2 f = new GetRefundFeeSfunc2();
        f.setAmount(amount);
        f.setCashFlow(cashFlow);

        return f.asField();
    }

    /**
     * Get <code>nw.get_refund_provider_fee</code> as a field.
     */
    public static AggregateFunction<Long> getRefundProviderFee(CashFlowRecord __1) {
        GetRefundProviderFee f = new GetRefundProviderFee();
        f.set__1(__1);

        return f.asAggregateFunction();
    }

    /**
     * Get <code>nw.get_refund_provider_fee</code> as a field.
     */
    public static AggregateFunction<Long> getRefundProviderFee(Field<CashFlowRecord> __1) {
        GetRefundProviderFee f = new GetRefundProviderFee();
        f.set__1(__1);

        return f.asAggregateFunction();
    }

    /**
     * Call <code>nw.get_refund_provider_fee_sfunc</code>
     */
    public static Long[] getRefundProviderFeeSfunc1(Configuration configuration, Long[] amounts, CashFlowRecord cashFlow) {
        GetRefundProviderFeeSfunc1 f = new GetRefundProviderFeeSfunc1();
        f.setAmounts(amounts);
        f.setCashFlow(cashFlow);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>nw.get_refund_provider_fee_sfunc</code> as a field.
     */
    public static Field<Long[]> getRefundProviderFeeSfunc1(Long[] amounts, CashFlowRecord cashFlow) {
        GetRefundProviderFeeSfunc1 f = new GetRefundProviderFeeSfunc1();
        f.setAmounts(amounts);
        f.setCashFlow(cashFlow);

        return f.asField();
    }

    /**
     * Get <code>nw.get_refund_provider_fee_sfunc</code> as a field.
     */
    public static Field<Long[]> getRefundProviderFeeSfunc1(Field<Long[]> amounts, Field<CashFlowRecord> cashFlow) {
        GetRefundProviderFeeSfunc1 f = new GetRefundProviderFeeSfunc1();
        f.setAmounts(amounts);
        f.setCashFlow(cashFlow);

        return f.asField();
    }

    /**
     * Call <code>nw.get_refund_provider_fee_sfunc</code>
     */
    public static Long getRefundProviderFeeSfunc2(Configuration configuration, Long amount, CashFlowRecord cashFlow) {
        GetRefundProviderFeeSfunc2 f = new GetRefundProviderFeeSfunc2();
        f.setAmount(amount);
        f.setCashFlow(cashFlow);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>nw.get_refund_provider_fee_sfunc</code> as a field.
     */
    public static Field<Long> getRefundProviderFeeSfunc2(Long amount, CashFlowRecord cashFlow) {
        GetRefundProviderFeeSfunc2 f = new GetRefundProviderFeeSfunc2();
        f.setAmount(amount);
        f.setCashFlow(cashFlow);

        return f.asField();
    }

    /**
     * Get <code>nw.get_refund_provider_fee_sfunc</code> as a field.
     */
    public static Field<Long> getRefundProviderFeeSfunc2(Field<Long> amount, Field<CashFlowRecord> cashFlow) {
        GetRefundProviderFeeSfunc2 f = new GetRefundProviderFeeSfunc2();
        f.setAmount(amount);
        f.setCashFlow(cashFlow);

        return f.asField();
    }
}
