name: Build Artifact

on:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Checkout GitHub Action Repo
        uses: actions/checkout@v2
        with:
          repository: alfaind/action-jdk-build
          ref: v1.0.17
          token: '${{ secrets.GITHUB_TOKEN }}'
          path: .github/actions/action-jdk-build
